### ISSUE TITLE
System.ArgumentException : An item with the same key has already been added.

### ISSUE THREAD

**Issue by pirovorster** [zzzprojects/EntityFramework-Extensions#10]
We are getting a exception when running unit tests in parallel on the bulk insert. Please see screenshot.

![image](https://cloud.githubusercontent.com/assets/6638988/17100912/be51b2fa-5271-11e6-854b-8ba22a28cd94.png)

**Comment by zzzprojects** [comment]
Thank you for reporting this issue.

We already found and fixed it.

However, we will take few hours to review the project and try to find if there is another potential, not thread-safe code.

A new release should be available later today.

**Comment by pirovorster** [comment]
Great. Please let me know when it is in.

**Comment by pirovorster** [comment]
Hi Guys. No updates yet?

**Comment by zzzprojects** [comment]
Sorry, I should have said the new version will be available tomorrow morning instead (or very late this night!).

**Comment by pirovorster** [comment]
Thanks for the quick response. Ok cool. We need it quite urgently but then we will have to wait.

**Comment by zzzprojects** [comment]
Hello,

The version v3.9.44 has been released fixing this issue.

All our test cannot, unfortunately, be run in parallel. So let us know if you found another method which is not yet thread-safe. We will make sure to fix it in priority.

**Comment by pirovorster** [comment]
Hi,

Cool. Now I am getting deadlocks on some of my tests.
![image](https://cloud.githubusercontent.com/assets/6638988/17130258/eea5bd42-5317-11e6-9761-4a733f4bf851.png)

**Comment by pirovorster** [comment]
![image](https://cloud.githubusercontent.com/assets/6638988/17130289/18fab1c4-5318-11e6-8ac3-ade6f1904ede.png)

**Comment by zzzprojects** [comment]
Hello,

Deadlock is unfortunately sometimes a "normal" behavior in a concurrent scenario. You may be surprised how easy is to create a deadlock.

It sometimes all depends on how the transaction is used.

I recommend you if your company does not already own one to have a tool to see more easily deadlock like this one: http://sqlsolutions.com/products/sql-deadlock-detector/index.html

You can send us by email the result if you want. This will help us to explain why this is happening.

You can also try with "SaveChanges", there is a good chance you get a deadlock with it as well. Even if our library is fast, long-running transaction is bad and may cause deadlock.

Let first check which is the statement that cause the DeadLock since we only know about the victim at this moment.

**Comment by zzzprojects** [comment]
Hello pirovorster,

Did you have the time to check about the deadlock?

We didn't receive anything from your part to help us to resolve this issue.

You can contact us directly for private information: info@zzzprojects.com

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Hello @pirovorster,

Did you have time to check about the deadlock?

Let us know if you prefer we close this issue.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Closing Issue: No answer
