### ISSUE TITLE
Object Reference Error Disabling a Global Filter with QueryFilterManager

### ISSUE THREAD

**Issue by tomaswinston** [zzzprojects/EntityFramework-Extensions#111]
Hi,

I am using the QueryFilterManger to set a filter on an object in my context.

In my context class I have the following code:
`QueryFilterManager.Filter<MasterClass>(Enums.QueryFilterEnum.MasterClass,q => q.Where(x => x.Deleted == false));`

I then want to temporarily disable this filter in my application before re-enabling it again.
To disable the filter I am doing the following but I am getting an "Object Reference Not Set to instance of an object" error.

`QueryFilterManager.Filter(Enums.QueryFilterEnum.MasterClass).Disable()`

Calling the disable on this `QueryFilterInterceptor<MasterClass>` throws an Null Object Reference Error.

Am I doing something wrong?

**Comment by tomaswinston** [comment]
For more information, here is the TargetSite and StackTrace..

`    Source: "Anonymously Hosted DynamicMethods Assembly"
    StackTrace: "   at lambda_method(Closure , DbContext , ObjectQuery )\r\n   at Z.EntityFramework.Plus.QueryFilterContextInterceptor.UpdateHook(DbContext context)\r\n   at Z.EntityFramework.Plus.QueryFilterManager.ClearAllCache()\r\n   at Z.EntityFramework.Plus.BaseQueryFilterInterceptor.Disable(Type[] types)\r\n   at Z.EntityFramework.Plus.BaseQueryFilterInterceptor.Disable()"
    TargetSite: {Void lambda_method(System.Runtime.CompilerServices.Closure, System.Data.Entity.DbContext, System.Data.Entity.Core.Objects.ObjectQuery)}`

Does this give you you any idea what the issue might be?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @tomaswinston ,

Do you think you could provide us a project example/test with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by tomaswinston** [comment]
Hi Jonathan,

After a lot of debugging I finally figured out the reason - my DbContext was implementing IDisposable which seemed to have unexpected consequences including the above.

Thanks
