### ISSUE TITLE
IdentityDbContext - supported?

### ISSUE THREAD

**Issue by wernerbarnard** [zzzprojects/EntityFramework-Extensions#116]
Haai,

If we have a context that extends IdentityDbContext instead of DbContext, can we use .BulkSaveChanges/Async ?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

Just to be sure, are you talking about the following `IdentityDbContext`: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.entityframeworkcore.identitydbcontext?view=aspnetcore-2.0 ?

If so, we will look at it if there is something we can do.

Best Regards,

Jonathan

**Comment by wernerbarnard** [comment]
Hi @JonathanMagnan 

That's the one - yes

**Comment by JonathanMagnan** [comment]
Thank you,

We will look at it today or tomorrow to determine the complexity of this request.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

We have investigated the `IdentityDbContext`

Unfortunately, due to all internal validation and additional logic implement in the `IdentityDbContext` class, we feel highly uncomfortable to try to support it.

So the answer is no, our library doesn't support it and we have to plan for now.

Best Regards,

Jonathan

**Comment by wernerbarnard** [comment]
Hi @JonathanMagnan 

Thanks, pity, but understood.
