### ISSUE TITLE
Database connection forcibly closed while bulk updating or inserting.

### ISSUE THREAD

**Issue by GitHubJMO** [zzzprojects/EntityFramework-Extensions#124]
I am getting an error when updating or inserting bulk records that have a large amount of data in specific columns. This error seems to be intermittent and does not occur on every update. I have also tried batching these updates in smaller amounts between 50 and 1000. The error occurs at the actual insert code itself. I also tried to use an update.

db.BulkInsert(myEntity); //This line errors

or

db.myEntity.AddRange(myCollection);
db.BulkSaveChanges(); //This line errors

 Error: provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.

Entity Framework 6.2.0
Z Entity Framework Extensions 3.15.5
Microsoft SQL database

**Comment by JonathanMagnan** [comment]
Hello @GitHubJMO ,

This kind of error is normally caused on the database server. I believe you already checked, but you can find a lot of similar error on Google.

It's often a network issue but a lot of cause can generate it. There is not so much we can do on our side since that's not our library that cause it.

How many entities in total do you try to insert? If you insert millions of entities, it's possible for you to batch them for example in batches of 50,000 entities?

Reducing the number of entities may help for this kind of issue.

Let me know if that helped you.

Best Regards,

Jonathan

**Comment by GitHubJMO** [comment]
I did find examples of the error on google but I was unable to find a solution that resolved my issue. I think my largest update is only around 30,000 entities. I have tried using smaller batches. I haven't experienced this type of error with the regular entity update methods. They seem to work without error albeit significantly slower. This is why I thought it might have something to do with your library doing something that might cause the database to close the connection.

**Comment by JonathanMagnan** [comment]
Hello @GitHubJMO ,

Do this error happen often? Are you able to easily repeat it in a dev environment? Is this with SQL Server or SQL Azure?

From some research, this error seems to appears often when the SqlBulkCopy fails.

It could be potentially caused when we make a SqlBulkCopy. Perhaps, there is something we do wrong that causes the issue on your side.

For example: Overflowing column: https://stackoverflow.com/a/42571386

**Comment by JonathanMagnan** [comment]
So it looks more to be a `network` / `firewall` issue or something like this.

I guess you will need a `DBA` on your side to help you on this one.

Can we close this issue? It doesn't look related to our library, so there is not so much we can do on our side on this.

**Comment by GitHubJMO** [comment]
Thank you for your time. You can close this issue.
