### ISSUE TITLE
Exception on SaveChanges when Table has Computed Column

### ISSUE THREAD

**Issue by jahn-swob** [zzzprojects/EntityFramework-Extensions#125]
I am attempting to add new records to a table and that table has two columns which are computed fields that execute a function.

The application is throwing an exception with this in the inner exception:
```json
{
    "Errors": [
        {
            "Source": ".Net SqlClient Data Provider",
            "Number": 4186,
            "State": 1,
            "Class": 16,
            "Server": ".",
            "Message": "Column 'inserted.PostedBalanceDue' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause.",
            "Procedure": "",
            "LineNumber": 14
        },
        {
            "Source": ".Net SqlClient Data Provider",
            "Number": 4186,
            "State": 1,
            "Class": 16,
            "Server": ".",
            "Message": "Column 'inserted.UnpostedBalanceDue' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause.",
            "Procedure": "",
            "LineNumber": 14
        }
    ],
    "ClientConnectionId": "99a593bb-059a-4674-afe1-3364495fbc58",
    "ClassName": "System.Data.SqlClient.SqlException",
    "Message": "Column 'inserted.PostedBalanceDue' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause.\r\nColumn 'inserted.UnpostedBalanceDue' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause.",
    "Data": {
        "HelpLink.ProdName": "Microsoft SQL Server",
        "HelpLink.ProdVer": "13.00.4206",
        "HelpLink.EvtSrc": "MSSQLServer",
        "HelpLink.EvtID": "4186",
        "HelpLink.BaseHelpUrl": "http://go.microsoft.com/fwlink",
        "HelpLink.LinkId": "20476"
    },
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\r\n   at System.Data.SqlClient.SqlDataReader.get_MetaData()\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)\r\n   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)\r\n   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)\r\n   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)\r\n   at Z.Data.SqlClient.SqlCommandSet.Execute()\r\n   at .(DbConnection , DbTransaction , List`1 )\r\n   at .Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nOnError\nSystem.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Data.SqlClient.SqlConnection\nVoid OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1[System.Action])",
    "HResult": -2146232060,
    "Source": ".Net SqlClient Data Provider",
    "WatsonBuckets": null
}
```

The top level exception has a message that says to use *EntityFrameworkManager.ForceSelectedOutput* to mitigate this issue, which then throws a different exception:

```json
{
    "ClassName": "System.ArgumentException",
    "Message": "Column 'Version_zzzinserted' does not belong to table Table.",
    "Data": {},
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Data.DataRow.GetDataColumn(String columnName)\r\n   at System.Data.DataRow.get_Item(String columnName)\r\n   at .( , DataTable )\r\n   at .( , DataTable )\r\n   at ..(DataTable )\r\n   at Z.Data.SqlClient.SqlCommandSet.Execute()\r\n   at .(DbConnection , DbTransaction , List`1 )\r\n   at .Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nGetDataColumn\nSystem.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Data.DataRow\nSystem.Data.DataColumn GetDataColumn(System.String)",
    "HResult": -2147024809,
    "Source": "System.Data",
    "WatsonBuckets": null,
    "ParamName": null
}
```

Not exactly sure why it is looking for a column that doesn't exist in a table called Table.  Anyway, is there any sort of guidance you can give here?

Thanks!

**Comment by JonathanMagnan** [comment]
Hello @jahn-swob ,

Are you able to send a project with this issue? So we could try it on our side.

Best Regards,

Jonathan

**Comment by jahn-swob** [comment]
Hi,

I’m going to try to create a separate project with just his issue intact.  Can’t send our main code base, so I’ll hopefully have something for you today so you can test it out.

Thanks,
-Jahn Swob

**Comment by jahn-swob** [comment]
I managed to re-create the issue in a console app.  It has all the necessary migrations to create the table, a UDF, and updating the columns to computed columns using the UDF. 

Here is the issue attached:
[ConsoleApp1.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/2202843/ConsoleApp1.zip)

I created two methods:
    * CreateRecord1 just shows the issue as its stated (cannot output the computed column sql exception 4186)
    * CreateRecord2 uses the ForceSelectOutput parameter and successfully saves, but updates to the entity causes the 'Version_zzzinserted' does not belong to the table Table exception to appear.

Let me know if you need anything else.
-Jahn

**Comment by JonathanMagnan** [comment]
Hello @jahn-swob ,

Just to let you know that we have found the cause and the solution.

A new version will be released later tomorrow with the fix.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @jahn-swob ,

The v3.15.7 has been released.

Let me know if everything works as expected

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
There is currently no way to do it for a single `BulkSaveChanges` operation but we will look at it if that can be possible ;)

**Comment by jahn-swob** [comment]
Awesome, looking forward to this in particular, this will fix every last bit of my problem.  I really appreciate how quickly you guys have responded to this issue.

Thanks again!

**Comment by jahn-swob** [comment]
Also, would this option extend as an option for BulkInsert as well?

**Comment by JonathanMagnan** [comment]
Hello @jahn-swob ,

The v3.15.11 has been released.

You can now specify the value in the options

Example:

```csharp
ctx.BulkSaveChanges(options => options.ForceSelectOutput = true);
ctx.BulkMerge(list, options => options.ForceSelectOutput = true);
```

If any value is true (global value or the method value), then the logic will be applied.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by jahn-swob** [comment]
Seems to be working as designed! Thanks again for your prompt responses!

**Comment by jahn-swob** [comment]
Ok, so apparently I jumped the gun.  When EF is referencing a Table it performs as expected.  But if EF is referencing a View with CREATE rights, it still has the same _"Column 'column' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause."_ exception message.

**Comment by JonathanMagnan** [comment]
Thank for the project, we will start to check it in a few minutes

**Comment by JonathanMagnan** [comment]
Hello @jahn-swob ,

Do this scenario work with `SaveChanges`? We don't mind supporting it even if `SaveChanges` doesn't work. It's more to make sure we do the right thing ;)

Yes, the table now created a table without these additional fields. Could you include the SQL Script about how tables/views should look? We added these computed fields to the table but in your text, you talk about a view.

Do you need this computer field value to be returned by the way?

**Comment by jahn-swob** [comment]
I'll have to check on if Save Changes works tomorrow morning.

So the migrations folder has all the necessary scripts to get the environment there. 

So the problem lies when you have a table in EF that is being overridden to look at a view using the modelBuilder. ToTable() method. Also the view has a computed column (that does not exist on the actual table) that has a sub query that references another physical table and queries it, either with an OUTER APPLY, Join, or CTE.

I even tried to create an INSTEAD OF INSERT trigger to see if it would handle it better and it doesn't. 

But to answer your last question, honestly, no the computed fields do not need to be returned in either the insert or update. 

I'll try to get back to you about the behavior of `SaveChanges`.

**Comment by JonathanMagnan** [comment]
Great,

Just, I will wait for your answer about `SaveChanges`

Meanwhile, I added a task to skip the computed column. Looking at the code, it should not be very hard on our side.

**Comment by jahn-swob** [comment]
Ok this is what I found out about the `SaveChanges` operation as it handles this particular issue:

* If you just change the `BulkSaveChanges` to `SaveChanges` with the models as they are currently defined it throws this particular exception:
```
{
    "ClassName": "System.Data.Entity.Infrastructure.DbUpdateException",
    "Message": "A null store-generated value was returned for a non-nullable member 'AmountAdded' of type 'ConsoleApp1.Context.Issue'.",
    "Data": null,
    "InnerException": {
        "ClassName": "System.Data.Entity.Core.UpdateException",
        "Message": "A null store-generated value was returned for a non-nullable member 'AmountAdded' of type 'ConsoleApp1.Context.Issue'.",
        "Data": null,
        "InnerException": null,
        "HelpURL": null,
        "StackTraceString": "   at System.Data.Entity.Core.Mapping.Update.Internal.PropagatorResult.AlignReturnValue(Object value, EdmMember member)\r\n   at System.Data.Entity.Core.Mapping.Update.Internal.PropagatorResult.SetServerGenValue(Object value)\r\n   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.BackPropagateServerGen(List`1 generatedValues)\r\n   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()\r\n   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)\r\n   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)\r\n   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()\r\n   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()\r\n   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\r\n   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)\r\n   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()\r\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\r\n   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)\r\n   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)\r\n   at System.Data.Entity.Internal.InternalContext.SaveChanges()",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": "8\nAlignReturnValue\nEntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Data.Entity.Core.Mapping.Update.Internal.PropagatorResult\nSystem.Object AlignReturnValue(System.Object, System.Data.Entity.Core.Metadata.Edm.EdmMember)",
        "HResult": -2146233087,
        "Source": "EntityFramework",
        "WatsonBuckets": null
    },
    "HelpURL": null,
    "StackTraceString": "   at System.Data.Entity.Internal.InternalContext.SaveChanges()\r\n   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()\r\n   at System.Data.Entity.DbContext.SaveChanges()\r\n   at ConsoleApp1.Program.CreateRecord2() in C:\\Users\\jahn\\source\\repos\\ConsoleApp1\\NewRepro\\ConsoleApp1\\Program.cs:line 41",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nSaveChanges\nEntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Data.Entity.Internal.InternalContext\nInt32 SaveChanges()",
    "HResult": -2146233087,
    "Source": "EntityFramework",
    "WatsonBuckets": null,
    "SafeSerializationManager": {
        "m_serializedStates": [
            {
                "InvolvesIndependentAssociations": false
            }
        ]
    },
    "CLR_SafeSerializationManager_RealType": "System.Data.Entity.Infrastructure.DbUpdateException, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
}
```

* So reading through the exception messages I tried changing the Entity model in the code on the computed columns to be nullable instead and added a new migration and emptied the contents so EF would accept the changes (because the view in SQL is already defined as nullable on the computed column).  So with the computed columns now nullable, the `SaveChanges` operation actually commits correctly, it just passes back `NULL` to the computed columns, which is acceptable on INSERT/UPDATE.

I hope this helps!

**Comment by jahn-swob** [comment]
Hi @JonathanMagnan, is there any update on this particular issue?

**Comment by JonathanMagnan** [comment]
Hello @jahn-swob ,

Thank you for the reminder, it looks we missed your last answer.

We are currently looking at it, the issue is caused because the `ForceSelectOutput` require a primary key and none can be found when using a `view`.

We are currently looking at what we can do since we still know the key from the `Entity Framework` model. I will give you another update very soon.

**Comment by JonathanMagnan** [comment]
Hello @jahn-swob ,

The v3.15.16 has been released.

We added some code to better manage the key in the view. Our code should now be able to find which column is the key by using the mapping provided by Entity Framework.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by jahn-swob** [comment]
@JonathanMagnan,

It looks like everything is working correctly with the ForceSelectOuput!  Thanks for taking the time to handle this particular edge-case!

**Comment by scsabalevente** [comment]
Hello,

I have the same issue here. Could you help me?
I use version 3.18.5 and ForceSelectOutput does not solves it:
`ctx.BulkSaveChanges(Function(options) options.ForceSelectOutput = True)`

Here is the error I get:
`{"The column reference ""inserted.DESCRIPTION"" is not allowed because it refers to a base table that is not being modified in this statement." & vbCrLf & "Column 'inserted.AR' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause." & vbCrLf & "The column reference ""inserted.ST_SHORT_DESC"" is not allowed because it refers to a base table that is not being modified in this statement."}`

SQL Server Profiler:
`exec sp_executesql N'MERGE INTO [RndSuite].[RndvEv] AS DestinationTable
USING
(
SELECT TOP 100 PERCENT * FROM (SELECT @0_0_0 AS [TR_SEQ], @0_0_1 AS [EV_SEQ], @0_0_2 AS [CREATED_ON], @0_0_3 AS [CLIENT_ID], @0_0_4 AS [APPLIC], @0_0_5 AS [DBAPI_NAME], @0_0_6 AS [EVMGR_NAME], @0_0_7 AS [OBJECT_TP], @0_0_8 AS [OBJECT_ID], @0_0_9 AS [OBJECT_IDS], @0_0_10 AS [OBJECT_LC], @0_0_11 AS [OBJECT_LC_VERSION], @0_0_12 AS [OBJECT_SS], @0_0_13 AS [EV_TP], @0_0_14 AS [USERNAME], @0_0_15 AS [EV_DETAILS], @0_0_16 AS ZZZ_Index
UNION ALL SELECT @0_1_0 AS [TR_SEQ], @0_1_1 AS [EV_SEQ], @0_1_2 AS [CREATED_ON], @0_1_3 AS [CLIENT_ID], @0_1_4 AS [APPLIC], @0_1_5 AS [DBAPI_NAME], @0_1_6 AS [EVMGR_NAME], @0_1_7 AS [OBJECT_TP], @0_1_8 AS [OBJECT_ID], @0_1_9 AS [OBJECT_IDS], @0_1_10 AS [OBJECT_LC], @0_1_11 AS [OBJECT_LC_VERSION], @0_1_12 AS [OBJECT_SS], @0_1_13 AS [EV_TP], @0_1_14 AS [USERNAME], @0_1_15 AS [EV_DETAILS], @0_1_16 AS ZZZ_Index) AS StagingTable ORDER BY ZZZ_Index
) AS StagingTable
ON 1 = 2
WHEN NOT MATCHED THEN
    INSERT ( [TR_SEQ], [EV_SEQ], [CREATED_ON], [CLIENT_ID], [APPLIC], [DBAPI_NAME], [EVMGR_NAME], [OBJECT_TP], [OBJECT_ID], [OBJECT_IDS], [OBJECT_LC], [OBJECT_LC_VERSION], [OBJECT_SS], [EV_TP], [USERNAME], [EV_DETAILS] )
    VALUES ( [TR_SEQ], [EV_SEQ], [CREATED_ON], [CLIENT_ID], [APPLIC], [DBAPI_NAME], [EVMGR_NAME], [OBJECT_TP], [OBJECT_ID], [OBJECT_IDS], [OBJECT_LC], [OBJECT_LC_VERSION], [OBJECT_SS], [EV_TP], [USERNAME], [EV_DETAILS] )
;
CREATE TABLE #ZZZProjects_dfc25dc5_fa6e_45c0_8ca8_86c0b2e44de2z ( [$action] VARCHAR(100) NULL, ZZZ_Index INT NULL, [DESCRIPTION_zzzinserted] nvarchar(80) COLLATE SQL_Latin1_General_CP1_CS_AS NULL, [AR_zzzinserted] char(1) COLLATE SQL_Latin1_General_CP1_CS_AS NULL, [ST_SHORT_DESC_zzzinserted] nvarchar(20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL );
MERGE INTO [RndSuite].[RndvSc] AS DestinationTable
USING
(
SELECT TOP 100 PERCENT * FROM (SELECT @1_0_0 AS [SC], @1_0_1 AS [ST], @1_0_2 AS [ST_VERSION], @1_0_3 AS [DESCRIPTION_MAIN], @1_0_4 AS [SHELF_LIFE_VAL], @1_0_5 AS [SHELF_LIFE_UNIT], @1_0_6 AS [SAMPLING_DATE], @1_0_7 AS [CREATION_DATE], @1_0_8 AS [CREATED_BY], @1_0_9 AS [EXEC_START_DATE], @1_0_10 AS [EXEC_END_DATE], @1_0_11 AS [PRIORITY], @1_0_12 AS [LABEL_FORMAT], @1_0_13 AS [IS_INTERVENTION], @1_0_14 AS [DESCR_DOC], @1_0_15 AS [DESCR_DOC_VERSION], @1_0_16 AS [SD], @1_0_17 AS [DATE1], @1_0_18 AS [DATE2], @1_0_19 AS [DATE3], @1_0_20 AS [DATE4], @1_0_21 AS [DATE5], @1_0_22 AS [ALLOW_ANY_PP], @1_0_23 AS [ALLOW_ANY_IP], @1_0_24 AS [LAST_COMMENT], @1_0_25 AS [SC_CLASS], @1_0_26 AS [LOG_HS], @1_0_27 AS [LOG_HS_DETAILS], @1_0_28 AS [ALLOW_MODIFY], @1_0_29 AS [ACTIVE], @1_0_30 AS [LC], @1_0_31 AS [LC_VERSION], @1_0_32 AS [SS], @1_0_33 AS [CONTEXT], @1_0_34 AS [SC_VALUE], @1_0_35 AS [ST_SHORT_DESC_MAIN], @1_0_36 AS ZZZ_Index) AS StagingTable ORDER BY ZZZ_Index
) AS StagingTable
ON 1 = 2
WHEN NOT MATCHED THEN
    INSERT ( [SC], [ST], [ST_VERSION], [DESCRIPTION_MAIN], [SHELF_LIFE_VAL], [SHELF_LIFE_UNIT], [SAMPLING_DATE], [CREATION_DATE], [CREATED_BY], [EXEC_START_DATE], [EXEC_END_DATE], [PRIORITY], [LABEL_FORMAT], [IS_INTERVENTION], [DESCR_DOC], [DESCR_DOC_VERSION], [SD], [DATE1], [DATE2], [DATE3], [DATE4], [DATE5], [ALLOW_ANY_PP], [ALLOW_ANY_IP], [LAST_COMMENT], [SC_CLASS], [LOG_HS], [LOG_HS_DETAILS], [ALLOW_MODIFY], [ACTIVE], [LC], [LC_VERSION], [SS], [CONTEXT], [SC_VALUE], [ST_SHORT_DESC_MAIN] )
    VALUES ( [SC], [ST], [ST_VERSION], [DESCRIPTION_MAIN], [SHELF_LIFE_VAL], [SHELF_LIFE_UNIT], [SAMPLING_DATE], [CREATION_DATE], [CREATED_BY], [EXEC_START_DATE], [EXEC_END_DATE], [PRIORITY], [LABEL_FORMAT], [IS_INTERVENTION], [DESCR_DOC], [DESCR_DOC_VERSION], [SD], [DATE1], [DATE2], [DATE3], [DATE4], [DATE5], [ALLOW_ANY_PP], [ALLOW_ANY_IP], [LAST_COMMENT], [SC_CLASS], [LOG_HS], [LOG_HS_DETAILS], [ALLOW_MODIFY], [ACTIVE], [LC], [LC_VERSION], [SS], [CONTEXT], [SC_VALUE], [ST_SHORT_DESC_MAIN] )
OUTPUT
    $action,
    StagingTable.ZZZ_Index,
    INSERTED.[DESCRIPTION] AS [DESCRIPTION_zzzinserted], INSERTED.[AR] AS [AR_zzzinserted], INSERTED.[ST_SHORT_DESC] AS [ST_SHORT_DESC_zzzinserted]
INTO #ZZZProjects_dfc25dc5_fa6e_45c0_8ca8_86c0b2e44de2z
;
SELECT * FROM #ZZZProjects_dfc25dc5_fa6e_45c0_8ca8_86c0b2e44de2z;
DROP TABLE #ZZZProjects_dfc25dc5_fa6e_45c0_8ca8_86c0b2e44de2z;
MERGE INTO [RndSuite].[RndvScAc] AS DestinationTable
USING
(
SELECT TOP 100 PERCENT * FROM (SELECT @2_0_0 AS [SC], @2_0_1 AS [UP], @2_0_2 AS [US], @2_0_3 AS [AR], @2_0_4 AS ZZZ_Index) AS StagingTable ORDER BY ZZZ_Index
) AS StagingTable
ON 1 = 2
WHEN NOT MATCHED THEN
    INSERT ( [SC], [UP], [US], [AR] )
    VALUES ( [SC], [UP], [US], [AR] )
;
MERGE INTO [RndSuite].[RndvUcHs] AS DestinationTable
USING
(
SELECT TOP 100 PERCENT * FROM (SELECT @3_0_0 AS [UC], @3_0_1 AS [VERSION], @3_0_2 AS [WHO], @3_0_3 AS [WHO_DESCRIPTION], @3_0_4 AS [WHAT], @3_0_5 AS [WHAT_DESCRIPTION], @3_0_6 AS [LOGDATE], @3_0_7 AS [WHY], @3_0_8 AS [TR_SEQ], @3_0_9 AS [EV_SEQ], @3_0_10 AS [DETAILS], @3_0_11 AS [LANG_ID], @3_0_12 AS ZZZ_Index) AS StagingTable ORDER BY ZZZ_Index
) AS StagingTable
ON 1 = 2
WHEN NOT MATCHED THEN
    INSERT ( [UC], [VERSION], [WHO], [WHO_DESCRIPTION], [WHAT], [WHAT_DESCRIPTION], [LOGDATE], [WHY], [TR_SEQ], [EV_SEQ], [DETAILS], [LANG_ID] )
    VALUES ( [UC], [VERSION], [WHO], [WHO_DESCRIPTION], [WHAT], [WHAT_DESCRIPTION], [LOGDATE], [WHY], [TR_SEQ], [EV_SEQ], [DETAILS], [LANG_ID] )
;
',N'@0_0_0 decimal(38,0),@0_0_1 decimal(38,0),@0_0_2 datetimeoffset(7),@0_0_3 nvarchar(20),@0_0_4 nvarchar(8),@0_0_5 nvarchar(40),@0_0_6 nvarchar(20),@0_0_7 nvarchar(10),@0_0_8 nvarchar(20),@0_0_9 nvarchar(2000),@0_0_10 
decimal(12,0),@0_0_11 decimal(12,4),@0_0_12 decimal(12,0),@0_0_13 nvarchar(60),@0_0_14 decimal(12,0),@0_0_15 nvarchar(max) ,@0_0_16 int,@0_1_0 decimal(38,0),@0_1_1 decimal(38,0),@0_1_2 datetimeoffset(7),@0_1_3 nvarchar(20),@0_1_4 nvarchar(8),@0_1_5 nvarchar(40),@0_1_6 nvarchar(20),@0_1_7 nvarchar(10),@0_1_8 nvarchar(20),@0_1_9 nvarchar(2000),@0_1_10 decimal(12,0),@0_1_11 decimal(12,4),@0_1_12 decimal(12,0),@0_1_13 nvarchar(60),@0_1_14 decimal(12,0),@0_1_15 nvarchar(max) ,@0_1_16 int,@1_0_0 decimal(12,0),@1_0_1 decimal(12,0),@1_0_2 decimal(12,4),@1_0_3 nvarchar(80),@1_0_4 decimal(3,0),@1_0_5 nvarchar(20),@1_0_6 datetimeoffset(7),@1_0_7 datetimeoffset(7),@1_0_8 decimal(12,0),@1_0_9 datetimeoffset(7),@1_0_10 datetimeoffset(7),@1_0_11 decimal(3,0),@1_0_12 nvarchar(20),@1_0_13 char(1),@1_0_14 nvarchar(80),@1_0_15 decimal(12,4),@1_0_16 decimal(12,0),@1_0_17 datetimeoffset(7),@1_0_18 datetimeoffset(7),@1_0_19 datetimeoffset(7),@1_0_20 datetimeoffset(7),@1_0_21 datetimeoffset(7),@1_0_22 char(1),@1_0_23 char(1),@1_0_24 nvarchar(255),@1_0_25 nvarchar(2),@1_0_26 char(1),@1_0_27 char(1),@1_0_28 char(1),@1_0_29 char(1),@1_0_30 decimal(12,0),@1_0_31 decimal(12,4),@1_0_32 decimal(12,0),@1_0_33 decimal(12,0),@1_0_34 nvarchar(20),@1_0_35 nvarchar(20),@1_0_36 int,@2_0_0 decimal(12,0),@2_0_1 decimal(5,0),@2_0_2 decimal(12,0),@2_0_3 char(1),@2_0_4 int,@3_0_0 decimal(12,0),@3_0_1 decimal(12,4),@3_0_2 decimal(12,0),@3_0_3 nvarchar(255),@3_0_4 nvarchar(60),@3_0_5 nvarchar(2000),@3_0_6 datetimeoffset(7),@3_0_7 nvarchar(255),@3_0_8 decimal(38,0),@3_0_9 decimal(38,0),@3_0_10 nvarchar(40),@3_0_11 decimal(2,0),@3_0_12 int',@0_0_0=5616,@0_0_1=1,@0_0_2='2019-06-04 14:59:06.6361308 +03:00',@0_0_3=N'13',@0_0_4=N'NG',@0_0_5=N'',@0_0_6=N'',@0_0_7=N'sc',@0_0_8=N'130',@0_0_9=N'<?xml version="1.0" encoding="utf-16"?>
<ArrayOfPrimaryKey xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <PrimaryKey>
    <Name>SC</Name>
    <Value xsi:type="xsd:decimal">130</Value>
  </PrimaryKey>
</ArrayOfPrimaryKey>',@0_0_10=NULL,@0_0_11=NULL,@0_0_12=NULL,@0_0_13=N'ScAnalysesCreated',@0_0_14=13,@0_0_15=N'<?xml version="1.0" encoding="utf-16"?>
<ArrayOfCustomKeyValuePairOfStringObject xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <CustomKeyValuePairOfStringObject>
    <Key>ST</Key>
    <Value xsi:type="xsd:decimal">2</Value>
  </CustomKeyValuePairOfStringObject>
  <CustomKeyValuePairOfStringObject>
    <Key>ST_VERSION</Key>
    <Value xsi:type="xsd:decimal">1.0000</Value>
  </CustomKeyValuePairOfStringObject>
</ArrayOfCustomKeyValuePairOfStringObject>',@0_0_16=0,@0_1_0=5616,@0_1_1=2,@0_1_2='2019-06-04 14:59:06.0751290 +03:00',@0_1_3=N'13',@0_1_4=N'NG',@0_1_5=N'',@0_1_6=N'',@0_1_7=N'sc',@0_1_8=N'130',@0_1_9=N'<?xml version="1.0" encoding="utf-16"?>
<ArrayOfPrimaryKey xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <PrimaryKey>
    <Name>SC</Name>
    <Value xsi:type="xsd:decimal">130</Value>
  </PrimaryKey>
</ArrayOfPrimaryKey>',@0_1_10=1,@0_1_11=5.0000,@0_1_12=1000000,@0_1_13=N'SampleCreated',@0_1_14=13,@0_1_15=N'<?xml version="1.0" encoding="utf-16"?>
<ArrayOfCustomKeyValuePairOfStringObject xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <CustomKeyValuePairOfStringObject>
    <Key>ST_VERSION</Key>
    <Value xsi:type="xsd:decimal">1.0000</Value>
  </CustomKeyValuePairOfStringObject>
</ArrayOfCustomKeyValuePairOfStringObject>',@0_1_16=1,@1_0_0=130,@1_0_1=2,@1_0_2=1.0000,@1_0_3=N'Sample_STL',@1_0_4=0,@1_0_5=NULL,@1_0_6='2019-06-04 14:58:59.1169634 +03:00',@1_0_7='2019-06-04 14:58:59.1169634 +03:00',@1_0_8=13,@1_0_9=NULL,@1_0_10=NULL,@1_0_11=NULL,@1_0_12=NULL,@1_0_13=NULL,@1_0_14=NULL,@1_0_15=NULL,@1_0_16=NULL,@1_0_17=NULL,@1_0_18=NULL,@1_0_19=NULL,@1_0_20=NULL,@1_0_21=NULL,@1_0_22='0',@1_0_23=NULL,@1_0_24=NULL,@1_0_25=NULL,@1_0_26='1',@1_0_27='0',@1_0_28='#',@1_0_29=NULL,@1_0_30=1,@1_0_31=5.0000,@1_0_32=1000000,@1_0_33=NULL,@1_0_34=N'SC20190604-31',@1_0_35=N'Sample_STL',@1_0_36=0,@2_0_0=130,@2_0_1=1,@2_0_2=NULL,@2_0_3='W',@2_0_4=0,@3_0_0=0,@3_0_1=0,@3_0_2=13,@3_0_3=N'SWQA\csaba.somogyi',@3_0_4=N'CodeMaskCreated',@3_0_5=N'Unique code with value ''SC20190604-31'' generated for sample type ''2'' with version ''1.0000''.',@3_0_6='2019-06-04 14:59:06.0741420 +03:00',@3_0_7=NULL,@3_0_8=0,@3_0_9=0,@3_0_10=NULL,@3_0_11=NULL,@3_0_12=0`


Can you help me, please?

Best Regards,
Csaba
