### ISSUE TITLE
UpdateFromQuery with complex types

### ISSUE THREAD

**Issue by LuisNebreda** [zzzprojects/EntityFramework-Extensions#149]
Hi,

We have one complex type in our entities in order to set it load status, it calls "LoadingInfo" of custom type "LoadInfo" and we set it into EntityFramework mapping:

```
Property(p => p.LoadingInfo.CreatedBy).HasColumnName("LoadCreatedBy");
Property(p => p.LoadingInfo.UpdatedBy).HasColumnName("LoadUpdatedBy");
```

But, we don't know how to inform it on update process, we try with:

```
uow.Set<Entity>().Where(x => x.ParentId == Id)
                .UpdateBulk(x => new Entity()
                {
                    LoadingInfo = new LoadInfo() { UpdatedBy = "User1" }
                });
```

but fails with error:

> System.InvalidOperationException: Sequence contains more than one matching element

We try a lot of different ways always with the same error, what is the right way to do that?

thanks

**Comment by JonathanMagnan** [comment]
Hello @LuisNebreda ,

Unfortunately `complex types` are not yet supported.

That's something on our roadmap since our paid library [EFE](http://entityframework-extensions.net/) started recently to support inheritance (TPC, TPH, TPT) but doesn't support complex type either yet.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @LuisNebreda ,

The v3.16.1 has been released. We should now support basic scenario with complex types.

Could you try it on your side and tell us if everything is now working?

Best Regards,

Jonathan
