### ISSUE TITLE
Error on BulkSaveChanges

### ISSUE THREAD

**Issue by walterborghi** [zzzprojects/EntityFramework-Extensions#164]
I use a kind of repoWrapper in my project and the following error occours when i try:

repo.myEntity.AddRange(listOfObjects); // here ok
repo.BulkSaveChanges();   // this line returns error below.

System.NullReferenceException: Object reference not set to an instance of an object.
   at .(BulkOperation this, DbContext )
   at .[](BulkOperation`1 this, DbContext , IEntityType , List`1 , BulkOperationActionType )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 )

I using EFCore 2.1 with Pomelo - MySQL.

**Comment by JonathanMagnan** [comment]
Hello @walterborghi ,

Do you think you could provide a project (info@zzzprojects.com) with your scenario? It could be a simple prototype throwing this error.

Since you are using an external library, we are not sure about how you use it and having an example will allow us to investigate this issue faster.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @walterborghi ,

Did you succeed to reproduce this issue in a standalone project?

**Comment by JonathanMagnan** [comment]
Hello @walterborghi ,

This issue will be closed but we will reopen it if you succeed to provide an example.

Best Regards,

Jonathan
