### ISSUE TITLE
Could not load file or assembly 'EntityFramework.MappingAPI

### ISSUE THREAD

**Issue by cbarnes199** [zzzprojects/EntityFramework-Extensions#171]
System.IO.FileLoadException: 'Could not load file or assembly 'EntityFramework.MappingAPI, Version=6.0.0.7, Culture=neutral, PublicKeyToken=7ee2e825d201459e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

I have entityframework.mappingapi 6.2 loaded and EntityFramework.BulkInsert 6.0.2.8 packages installed.

**Comment by JonathanMagnan** [comment]
Hello @cbarnes199 ,

`EntiytFramework.BulkInsert` is no longer supported since `2014`. The `MappingAPI` doesn't longer work with this library so in short, it doesn't work at all.

We now only support `Entity Framework Extensions`. It's not free but it supports more provider and offers way more operations such as:

- BulkSaveChanges
- BulkInsert
- BulkDelete
- BulkUpdate
- BulkMerge

Let me know if that answer to your question.

Best Regards,

Jonathan

**Comment by cbarnes199** [comment]
So is the mappingAPI also no longer supported?

**Comment by JonathanMagnan** [comment]
Hello @cbarnes199 ,

Both libraries are no longer supported. We have no plan to support them in the future either.
