### ISSUE TITLE
Optimistic concurrency check missing for .NET CORE version?

### ISSUE THREAD

**Issue by idesfosses** [zzzprojects/EntityFramework-Extensions#178]
Dear,

On https://entityframework-extensions.net/concurrency, the documentation describes how the BulkUpdate and BulkSaveChanges methods throw DbUpdateConcurrencyException if records have been altered by a different process.

I was able to use this functionality in the .NET framework version (combined with EF6), but am missing this feature in the .NET CORE version. Are there any plans on adding this feature to the .NET CORE version?

Thanks in advance for your answer.

Kind regards,

Igor Desfossés

**Comment by JonathanMagnan** [comment]
Hello @idesfosses ,

Thank you for reporting.

We will look at it and what is missing on our side.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @idesfosses ,

The v2.1.46 has been released.

We implemented the `Concurrency` for `BulkSaveChanges`

We are not sure at this moment if we want to implement it or not in the `Bulk Update`. The main reason is that we noticed that people usually don't have the `Old` concurrency value (the one in the database), and most people were repeatedly reporting us this error.

That's why we currently only added it on `BulkSaveChanges`.

Let me know if everything is now working as expected.

Best Regards,

Jonathan

**Comment by idesfosses** [comment]
@JonathanMagnan,

Great work. After some testing I can confirm that the functionality works as I expected.

Having it as part of the BulkSaveChanges will be sufficient for me.

Thanks for the quick implementation.

Kind regards,
Igor Desfossés
