### ISSUE TITLE
Cast from type WhereSelectListIterator`2[?,System.Object]

### ISSUE THREAD

**Issue by snakeface91** [zzzprojects/EntityFramework-Extensions#197]
Calling BulkSaveChanges to add 2 records i got :

Impossible d'effectuer un cast d'un objet de type 'WhereSelectListIterator`2[,System.Object]' en type 'System.Collections.Generic.IEnumerable`1[System.Data.Entity.Core.Mapping.Update.Internal.UpdateCommand]'.

**Comment by JonathanMagnan** [comment]
Hello @snakeface91 ,

It's possible to provide the stack trace? Is there something special in your context?

It looks what you are doing is very basic so we don't expect an error either.

**Comment by snakeface91** [comment]
à .Execute()
   à DbContextExtensions.BulkSaveChanges(DbContext this)
   à TestEntity.Program.Main(String[] args) dans C:\TFS_ada\Batchs\NewRef\Feeds\TestEntity\Program.cs:ligne 66

**Comment by snakeface91** [comment]
à lambda_method(Closure , Object , IEnumerable )
   à .()
   à .Execute()

**Comment by JonathanMagnan** [comment]
Thank you,

I believe we know exactly where is the issue. However, we still don't know how to reproduce it.

Which version of Entity Framework are you using? We will run all our unit test with this version, perhaps there is something different.

**Comment by snakeface91** [comment]
Version is 6.2.0 of EntityFramework (latest)

**Comment by JonathanMagnan** [comment]
Thank you for your project,

We successfully reproduced the issue and the cause.

Even if `SaveChanges`, your save doesn't work and throw the following error message:

> Additional information: Unable to determine a valid ordering for dependent operations. Dependencies may exist due to foreign key constraints, model requirements, or store-generated values.

In our case, this part of the code that throws the error has never been tested and never happened to use before, so an invalid cast error was throw instead of the same error as above.

Did you report that issue because the error message was wrong or because you thought it was supposed to work?

We are currently trying to fix this error message.

**Comment by JonathanMagnan** [comment]
Just to let you know, the issue is now fixed on our side and will be part of the next deployment.

As said, the error message unrelated to our library is still throwing.

**Comment by snakeface91** [comment]
Hi Jonathan,
It's ok you had showed me de bug tks!
It works now.
