### ISSUE TITLE
BulkSaveChanges() isn't accessible from custom Context class that inherits from IdentityDbContext

### ISSUE THREAD

**Issue by brunodejelaivly** [zzzprojects/EntityFramework-Extensions#231]
### Description
I believe your extension only works against Context class, but in my case, I'm extending IdentityDbContext, which doesn't allow me to reference BulkSaveChanges() - it's visible, but can't be referenced as it's on the grandparent class Context. 

Would it be possible to make a similar extension that attached to IdentityDbContext instead?

### Fiddle or Project
https://dotnetfiddle.net/0DIE4K

### Further technical details
- EF version: 6.0.0
- EF Extensions version: 3.20.5.0
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @brunodejelaivly ,

Thank you for reporting.

We will look at it if there is something we can do or not with the `IdentityDbContext`.

Best Regards,

Jonathan

**Comment by jahn-swob** [comment]
As a workaround, I believe you can cast the IdentityDbContext as a DbContext and then use BulkSaveChanges().  Something to the effect of:
```
public void BulkSaveChanges()
{
    ((System.Data.Entity.DbContext)this).BulkSaveChanges();
}
```

**Comment by JonathanMagnan** [comment]
Hello @brunodejelaivly ,

Did you try @jahn-swob  solution?

In fact, I don't think the casting is even needed. I believe your Fiddle was not working because you tried to `override` a method that doesn't exist.

On our side, we downloaded the project `Microsoft.AspNet.Identity` and run all test using `BatchSaveChanges` and `BulkSaveChanges` and everything worked.

Here is an example of how you could create your context

```csharp
public class MyContext : IdentityDbContext<User, Role, int, UserLogin, UserRole, UserClaim>
{
	public MyContext(): base ("name=MyDB")
	{
	}

	public override int SaveChanges()
	{
		return this.BatchSaveChanges();
		//return base.SaveChanges();
	}

	public int BatchSaveChanges()
	{
		return this.BatchSaveChanges();
	}

	public void BulkSaveChanges()
	{
		this.BulkSaveChanges();
	}
}
```
https://dotnetfiddle.net/3diufP

Let me know if you need more help.
