### ISSUE TITLE
Delete() where query has <= datetime doesn't always work

### ISSUE THREAD

**Issue by PhilPJL** [zzzprojects/EntityFramework-Extensions#238]
[Demo.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/3341792/Demo.zip)

### Description

Using .Delete like this `context.Tests.Where(t => t.Date <= dbNow).Delete();` doesn't always work as expected.

Run the demo app a few times.  Sometimes it will delete 4 rows (as expected), sometimes 0.

### Further technical details
- EF version: 6.2
- EF Extensions version: 3.21.1
- Database Provider: SQL Server 14.0.2014.14

**Comment by JonathanMagnan** [comment]
Hello @PhilPJL ,

Unfortunately, I would say "work as intended".

That's a `DateTime` vs `DateTime2` issue

Your column type is a `DateTime` but Entity Framework use a `DateTime2` column in parameter (and so for our library).

However, value are not always equal...

```sql
DECLARE @date1 DATETIME = '2019-06-29 07:48:25.873'
DECLARE @date2 DATETIME2 = '2019-06-29 07:48:25.8730000'

-- return nothing
SELECT 1 
WHERE @date1 <= @date2

DECLARE @date3 DATETIME = '2019-06-29 07:48:25.874'
DECLARE @date4 DATETIME2 = '2019-06-29 07:48:25.8740000'

-- return 1
SELECT 1 
WHERE @date3 <= @date4

-- round issue...
SELECT CAST(@date1 AS DATETIME2),
CAST(@date3 AS DATETIME2)
```

That's caused because how SQL round DATETIME to DATETIME2

`2019-06-29 07:48:25.873` is rounded to `2019-06-29 07:48:25.8733333` which is greater then the date specified. `2019-06-29 07:48:25.874` is rounded to `2019-06-29 07:48:25.8733333` which is lower than the date specified.

It left us with 2 options:
- Make a change to your database to use DATETIME2 everywhere (Recommanded since you should never use DATETIME)
- Ask us to add an options for the `UpdateFromQuery`, every time we would have put a DateTime2 in column type, we will instead put a DateTime type (We will need to test it but I believe it might work).

Let me know if that explain correctly the current "random" issue.

**Comment by PhilPJL** [comment]
Thanks for the quick response, and sorry that I was too quick to assume that this must be a bug in your code.  I've verified that a simple EF query has the same problem.

Yes agreed, it's a bad habit to use the DateTime type without specifying a column type of DATETIME2.
I'll switch to DateTimeOffset that fixes it.
