### ISSUE TITLE
DeleteFromQuery doesn't return the number of rows affected

### ISSUE THREAD

**Issue by JendaPerl** [zzzprojects/EntityFramework-Extensions#243]
Is there any reason the DeleteFromQuery doesn't return the number of affected rows? At least for the databases/drivers that provide such info.

**Comment by JonathanMagnan** [comment]
Hello @JendaPerl ,

I don't think there is any **good reason**.

I believe `BulkInsert` and other bulk methods doesn't provide the affected rows (was too hard to support at the beginning due to all possibles options), so we took the same decision about `DeleteFromQuery` and it never has been added.

We will look at it to at least add this information for `DeleteFromQuery` and `UpdateFromQuery`. Most of the logic is already here to support it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JendaPerl ,

The v3.21.5 has been released.

Both methods now return the number of rows affected.

Could you try it and let us know that everything works as expected.?

**Comment by JendaPerl** [comment]
I only see 3.21.2 of Z.EntityFramework.Extensions.Classic, even if I check "Include prerelease". Could it be because I'm still on .Net Framework 4.6.2?

**Comment by JonathanMagnan** [comment]
Hello @JendaPerl ,

No, that's because the EFE for EF Classic has not been released yet. We just did it for EF6 and EF Core.

A release is already planned during the weekend so we let you know as soon as this version is available.

**Comment by JonathanMagnan** [comment]
Hello @JendaPerl ,

`EF Classic` is now up to date.

Let me know if that's now working as expected.

**Comment by JendaPerl** [comment]
It throws NullReferenceExceptions :-(
Details in the new issue.

**Comment by JonathanMagnan** [comment]
Can we close this one? Since you closed: https://github.com/zzzprojects/EntityFramework-Extensions/issues/259#event-2561977331
