### ISSUE TITLE
System.OutOfMemoryException error

### ISSUE THREAD

**Issue by rasimcetin** [zzzprojects/EntityFramework-Extensions#300]
In our project we want to make data transportation from one database to another.
We are getting System.OutOfMemoryException error because of that the data is too big.
Do you have a solution for this problem.

- EF Core version: 2.2.4.0
- EF Extensions.EFCore version:2.7.3.0
- Database Provider: SQL Server 2014

**Comment by rasimcetin** [comment]
This the stack trace;

at System.Text.StringBuilder.ToString()
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.GetCommandText()
at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.GetCommandText()
at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.IsCommandTextValid()
...
...
...
at DbContextExtensions.BulkInsert(DbContext this, IEnumerable'1 entities, Action'1 options)

**Comment by JonathanMagnan** [comment]
Hello @rasimcetin ,

Look like the issue happen directly in `EF Core` code base on a string builder which is very strange.

How exactly your `data is too big`? It's because of having too many rows, too many properties? or something else?

To have the method `GetCommandText` on a `StringBuilder` throw an out of memory exception, it looks something in your application makes to generate a very big string.

Let me know more about your scenario to give us some hint on how to reproduce it,

Looking forward to hearing from you, 
 
Jon

**Comment by rasimcetin** [comment]
Hi Jon,

We have very big hierarchical entity. It has 6 level. Every entity in this hierarchy has lots of child entity as list. Also these entities have nearly 30-40 properties. We are trying to move these entities from one database to another. Total number of rows in this data is nearly 230.000. 

You may be right about the reason of this error is EF Core not EF-Extensions. We have found a temporary solution for now. I just want to learn do you have a solution for like these problems.

Thanks,

**Comment by JonathanMagnan** [comment]
At this moment, I'm not sure exactly what's the problem as I don't see why the StringBuilder would go out of memory here.

But by looking at the stack trace, it happens when batching command `ReaderModificationCommandBatch`.

So perhaps disabling batching could help. Here is a solution for SqlServer

```csharp
protected override void OnConfiguring(DbContextOptionsBuilder optionbuilder)
{
    string sConnString = @"Server=localhost;Database=EFSampleDB;Trusted_Connection=true;";
    optionbuilder.UseSqlServer(sConnString , b => b.MaxBatchSize(1));
}
```

_(Might exists a better way to disable it)_

Let me know if that worked.

**Comment by rasimcetin** [comment]
Hi Jon 
We have solved the problem by splitting data into small partitions to insert.
