### ISSUE TITLE
Malware Name: Trojan:Win32/Detplock

### ISSUE THREAD

**Issue by clabough** [zzzprojects/EntityFramework-Extensions#307]
My system administrator just alerted me to this after I upgraded to 4.0.20.  Reverting back to 4.0.19 it does not get flagged.

> System Center Endpoint Protection has detected malware on one or more computers in your organization 
> 
> Malware Name: Trojan:Win32/Detplock
> 
> Malware file path: file:_D:\WebRoot\myapp\bin\Z.EntityFramework.Extensions.dll

**Comment by clabough** [comment]
Probably a false-positive, but as long as it's getting flagged, it's getting quarantined.

**Comment by JonathanMagnan** [comment]
Hello @clabough ,

It's the first time you upgrade or you use a different version then v4.0.19?

We will contact you next time we make a release (should be this week) but I don't think there is really anything we can do on our side ;(

My developer will still look at it tomorrow to better understand what could cause this.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @clabough ,

The v4.0.21 has been released.

Could you try it and let us know if our library is still flagged as a trojan.

On our side we checked with some anti-virus and everything seem to be fine. So we are not really sure what to do at this moment since that's the first time someone report us something like this.

**Comment by clabough** [comment]
I upgraded to v4.0.22 and it's not getting flagged anymore.
