### ISSUE TITLE
Support Firebird

### ISSUE THREAD

**Issue by Franki1986** [zzzprojects/EntityFramework-Extensions#31]
Do you have plans to support firebird databases?

**Comment by JonathanMagnan** [comment]
Hello @Franki1986 ,

Supporting Firebird is for sure on our wish list. However, we don't have any plan at this moment to support it soon.

We are currently re-writing the next major version of our library. If we support it, it will be in that version.

Let me know if that answered correctly to your question.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Franki1986 ,

We will close this request as we don't have a timeline for the support for `Firebird`.

The good news is that we already support it for the following libraries:
- Bulk Operations: https://bulk-operations.net/
- Dapper Plus: https://dapper-plus.net/

We keep it open in our internal issue tracker so that's for sure something we will look again as most code is probably already done do allow to support it.

Best Regards,

Jonathan
