### ISSUE TITLE
Add .NET Standard 2.0 target for v4.x

### ISSUE THREAD

**Issue by MikeFarrington** [zzzprojects/EntityFramework-Extensions#314]
Our project is starting the process of moving from .NET Framework to .NET Core via .NET Standard 2.0.

v4.x for EF6 only targets .NET Standard 2.1, and nothing lower.  .NET Standard 2.1 has dropped compatibility with .NET Framework.

If Z.EntityFrameworks.Extensions was able to also target .NET Standard 2.0, it would allow us to take a careful piecemeal approach by switching our class libraries to .NET Standard 2.0 before bringing other consuming code up to some version of .NET Core.  

By only supporting .NET Standard 2.1, it makes the work to move away from .NET Framework very difficult.  If at all possible, a .NET Standard 2.0 target would be a necessary bridge for users of this extension who are navigating their way to .NET Core.

**Comment by JonathanMagnan** [comment]
Hello @MikeFarrington ,

We support .NET Standard 2.1 since that's the minimum version EF v6.4 support if you look at the dependencies section: https://www.nuget.org/packages/EntityFramework/6.4.0

Switching from 2.1 to 2.0 is very easy for us. However, it requires EF 6 to support .NET Standard 2.0 as well.

So I believe you need first to contact the `Microsoft` team or use [Entity Framework Classic](https://entityframework-classic.net/) that support .NET Standard 2.0

Perhaps I'm missing something in your request? In the .NET Framework, the dll from the v4.5 dependencies should be taken from our library.

**Comment by MikeFarrington** [comment]
I looked into this a little more, and the EntityFramework nuget package for 6.4 also doesn't target 2.0 like I thought it did.  However, it doesn't throw all kinds of errors when you try add it to a .NET Standard 2.0 project the way this one does..

**Comment by MikeFarrington** [comment]
@JonathanMagnan 

Here is the output I get from the package manager console:
`Restoring packages for C:\Users\Michael Farrington\ComPAS.MainClient\ComPAS.Data\ComPAS.Data.csproj...
NU1701: Package 'Z.EntityFramework.Extensions 4.0.34' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
Package restore failed. Rolling back package changes for 'ComPAS.Data'.
Time Elapsed: 00:00:03.2688747
========== Finished ==========`

**Comment by JonathanMagnan** [comment]
Not so much we can do here ;) Look more like how NuGet/Visual Studio handle it.

In any case, it's impossible due to having to use minimum `.NET Standard 2.1`.
