### ISSUE TITLE
Z.EntityFramework.Extensions.EFCore BulkInsert on Oracle database not using sequence/trigger

### ISSUE THREAD

**Issue by Douuuglas** [zzzprojects/EntityFramework-Extensions#315]
### Description
Hello,
I'm using the last version of Z.EntityFramework.Extensions.EFCore for EF Core 2 with an Oracle database. I have a table that have a trigger that triggers a sequence to insert the key value.
But when i use the BulkInsert method it's not calling the trigger/sequence, it tries to save "0" at the key, so i get a PK error. I did the same thing with Z.EntityFramework.Extensions for EF, not core, and it works.

So, what i did, i changed to "AddRange" + "BulkSaveChanges", it's slower but works, and i'm openning this issue to see if you can help me 😄  

### Database script:
CREATE TABLE TFCT_AUD_APUR_IMPOSTOS
            (
               ID_APUR_IMPOSTOS int NOT NULL,
               CONSTRAINT PK_TFCT_AUD_APUR_IMPOSTOS PRIMARY KEY 
               (
                  ID_APUR_IMPOSTOS 
               )
            )

CREATE SEQUENCE SEQ_TFCT_AUD_APUR_IMPOSTOS START WITH 1 INCREMENT BY 1 NOCACHE

CREATE OR REPLACE TRIGGER TG_TFCT_AUD_APUR_IMPOSTOS BEFORE INSERT ON TFCT_AUD_APUR_IMPOSTOS FOR EACH ROW BEGIN IF(:new.ID_APUR_IMPOSTOS IS NULL) THEN SELECT SEQ_TFCT_AUD_APUR_IMPOSTOS.NEXTVAL INTO :new.ID_APUR_IMPOSTOS FROM DUAL; END IF; END;

### C# EntityConfiguration:
public class ApuracaoImpostosConfiguration : IEntityTypeConfiguration<ApuracaoImpostos>
    {
        public void Configure(EntityTypeBuilder<ApuracaoImpostos> builder)
        {
            builder.ToTable("TFCT_AUD_APUR_IMPOSTOS");
            builder.HasKey(p => p.IdApurImpostos);
            builder.Property(p => p.IdApurImpostos).HasColumnName("ID_APUR_IMPOSTOS").ValueGeneratedOnAdd();
        }
    }

### C# Entity:
 public class ApuracaoImpostos
    {
       public int IdApurImpostos { get; set; }
    }

### C# BulkInsert:
_apuracaoImpostosRepository.BulkSaveChanges(apuracoesImpostos); //apuracoesImpostos is an IEnumerable<ApuracaoImpostos> with IdApurImpostos = 0

### Further technical details
- EF Core version: Microsoft.EntityFrameworkCore 2.2.6 
- EF Extensions version: Z.EntityFramework.Extensions.EFCore 2.7.36
- Database Provider: Oracle.ManagedDataAccess.Core 2.19.60

**Comment by JonathanMagnan** [comment]
Hello @Douuuglas ,

Yes, that's a known problem on our side. Since a trigger is used, we cannot retrieve if the column is an identity or not.

Here is a workaround

```csharp
context.BulkInsert(list, options => options.PostConfiguration = bulk => {
                bulk.ColumnMappings.Single(x => x.SourceName == "ID_APUR_IMPOSTOS").IsIdentity = true;
});
```

We will look if we could improve the mapping on our side for Oracle or why the `ValueGeneratedOnAdd` doesn't work.

I believe a mapping such as the one you provide should have enough information to assume that the property ID_APUR_IMPOSTOS is an identity.

I will keep you updated.

Best Regards,

Jon

**Comment by gurmeetsg** [comment]
Is this issue resolved ? I am facing similar issue for Oracle and the above mentioned solution does not work for me.

**Comment by deniscesar** [comment]
Hello @JonathanMagnan 

Is this extension ready to use UseHiLo("SEQUENCE") in EF core 3.1 in Oracle ?

When following the above recommendation I still have an error when bulkInsert

`Sequence contains no matching element -    at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable 1 source, Func 2 predicate)`

**Comment by JonathanMagnan** [comment]
Hello @deniscesar ,

Sorry, we missed your question.

He was not aware of this configuration, so I doubt our library support it.

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @deniscesar ,

Sorry for the delay. Unfortunately due to how our library work, we didn't successfully make it works.

However, as you find out, the `BulkSaveChanges` work differently than `BulkInsert` and already support it since we directly get value from Entity Framework.

Another way to make it works is to use `BulkInsert` with `IncludeGraph`:

```csharp
_apuracaoImpostosRepository.BulkInsert(apuracoesImpostos, options => options.IncludeGraph = true);
```

Under the hood, the same strategy as BulkSaveChanges is used when IncludeGraph is enabled, so it also works.

It might not be impossible that we try again later but for now, you will have to use one of the two alternative solutions.

Best Regards,

Jon
