### ISSUE TITLE
BulkUpdate question

### ISSUE THREAD

**Issue by meeper34** [zzzprojects/EntityFramework-Extensions#326]
This isn't a bug, but more a question of the functionality.  I may be asking for the moon here, but with your BulkUpdate, is it possible to update a table with a query?  For example "UPDATE Table Set Field = X WHERE Y = Z".  The data I have is not selected (I don't have a DataTable), and I don't have a DbSet because my table is dynamically created (but the table would be large so bulk updating would greatly help).  I know there are ways to do this by selecting the data into a temp table and then using that table to do the update.  I wasn't sure if there was a way to do this using your library.

Thanks for the help!

**Comment by JonathanMagnan** [comment]
Well, in fact, it looks pretty similar to what we want to achieve very soon.

We probably already did a similar request from our new method: `InsertFromQuery`.

This is possible to make a query from a `DbSet` and insert it in any table.

For example:

```csharp
context.Customers
    .Where(x => x.IsActive && x.LastLogin < date)
    .InsertFromQuery("bck_Customer", x => new { x.CustomerID, x.Name, x.Email });
```

Is it something like this you want but for `BatchUpdate`? You perform a query on a DbSet and with the result, update another table.

Please let me know which version of Entity Framework you are using (EF6 or EF Core 3.x)?

I will check with my team next week when we plan to complete this request.

**Comment by meeper34** [comment]
It's similar, but I don't have a DbSet at all in my case.  I'm basically hoping for a generic way to bulk update a large table without having that table in memory anywhere (like I said asking for the moon)!  I figure you already have the internals your library for creating a temp table and bulk inserting into it.  This is probably an edge case, I just wanted to check.

Something like this:
https://stackoverflow.com/questions/44166544/fastest-way-of-performing-bulk-update-in-c-sharp-net

That example looks like it has an in memory collection of items, though.

I'm not even 100% sure the performance would be better; it's something I wanted to test out.

I'm using 6.2.0.

**Comment by JonathanMagnan** [comment]
Just to let you know that I will have a meeting with one of my developers about it.

I will tell you more once we make a decision about it.

**Comment by JonathanMagnan** [comment]
Hello @meeper34 ,

I discussed it with my developer. The current situation is that we cannot afford a big development at this moment since we have too many projects

However, we could still help you to get solved as we already have some tricks on our sleeves to make it or perhaps we already support it.

### Do you have a class that represent your database table?

If yes, maybe our bulk operations library (which is already included in EFE) might already do the job: https://bulk-operations.net/update-from-query

As it doesn't require the entity type to be mapped to the context.

### Is a solution with an expando object/dynamic/anonymous type could work for you?

For this one, we will need to check with the Bulk Operations library. We started to support multiple types such as anonymous type in the `Batch Update` for EFE but nothing has been done for this library yet.

If yes, let me know or give an example of how you would like to do it.

---

If you want something else, please show us an example of how you would like to use it in your best case scenario (I don't think any of the code provided from your link work as you cannot specify value or create sql formula).

If that's too complex, we might still help you by doing a small side project for this kind of situation. 

As said, we probably have the solution for your case. Providing a solution that is outside of our library is way easier/faster than adding the code to our library since it comes with a lot of overhead (architecture, unit test, options, etc.).

**Comment by JonathanMagnan** [comment]
Hello @meeper34,

This issue will be closed since we haven't heard back from you.

However, don't hesitate to contact us once you'll be able to provide more information.

Best Regards,

Jon
