### ISSUE TITLE
AllowDuplicateKeys doesn't appear to always work

### ISSUE THREAD

**Issue by atkulp** [zzzprojects/EntityFramework-Extensions#353]
Using EF Core, when I try to bulk merge with a small number of rows, `AllowDuplicateKeys = false` seems to work, but with a larger set it doesn't error on the them.  It looks like the staging table isn't created with a constraint, so maybe that's all that's needed.  I don't want to proceed with the merge operation if there are any duplicates and I'm hoping there's a way to do that without screening the data first.  I thought maybe I could inject my own statement to run between the bulk load and the actual merge (maybe using BulkOperationExecuting) but that doesn't look like it's right, so I think it needs to be done in the extension code.

**Comment by JonathanMagnan** [comment]
Hello @atkulp ,

Unfortunately, the options don't work as you think.

By default, in the same batch, you cannot have multiple times the same key due to some SQL Server limitations with the MERGE statement. When enabling this option, we will make a select (affect performance) and make sure only the latest row with the same key is taken. So that doesn't work at all like you want.

We will look at it and add a new option that will fit your requirement which will validate that all rows have a unique key before going further.

Best Regards,

Jon

**Comment by atkulp** [comment]
Thank you for the explanation. It would be great if you could implement truly unique.  Thank you!

**Comment by JonathanMagnan** [comment]
Hello @atkulp ,

A new option named `ValidateNoDuplicateKey` has been added.

This option will validate that the source has no duplicate key before going further as you asked.

Could you try it and let us know if everything is working as expected?

Best Regards,

Jon

**Comment by atkulp** [comment]
Thanks!  I hope to give this a try over the next few days.

**Comment by JonathanMagnan** [comment]
Awesome @atkulp 

We will be looking forward to hearing from you once you give it a try!

Best regards,

Jon

**Comment by atkulp** [comment]
Looks great!  Thanks for your work on that!  With the two similarly named properties, it makes it all the more important to have very clear documentation on how to use the two now...
