### ISSUE TITLE
Z.EntityFramework.Extensions dependency on System.Data.Linq (Tested 3.16.16, 3.22.7, 4.0.106, 5.1.3)

### ISSUE THREAD

**Issue by BlairMcc** [zzzprojects/EntityFramework-Extensions#375]
### Description
Z.EntityFramework.Extensions dependency on System.Data.Linq (Tested 3.16.16, 3.22.7, 4.0.106, 5.1.3)

We are finding we are getting this error when attempting to call common code from a .Net Core 3.1 Windows Service using TopShelf

The code as which it fails look like this - 

```context.filters.Where(x => x.key == thisKey).DeleteFromQuery();```

Is there a way we can work around this? We were getting System.Runtime.Caching errors which were resolving by adding System.Runtime.Cachcing 5.0.0 to the running console, but this is a bit trickier. 

### Exception
```
Processor.Console.Plugins.PluginExecutor[0]
      Error running operation Plugin
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System.Data.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at ?.?(? ?)
   at ?.Execute(List`1 actions)
   at ?.?(List`1 ?)
   at Z.BulkOperations.BulkOperation.?()
   at Z.BulkOperations.BulkOperation`1.DeleteFromQuery(IQueryable originalQuery, IQueryable query)
   at DbContextExtensions.?[?](IQueryable`1 ?, Action`1 ?, CancellationToken ?)
   at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query, Action`1 bulkOperationFactory)
   at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query)
   at Common.CommonDataCreation.BulkInsertFilters(List`1 filters, Int64 key) in C:\dev\Common\CommonDataCreation.cs:line 484
```

### Further technical details
- EF version: 6.4.4
- EF Extensions version: ???
- Database Provider: SQL Server

**Comment by BlairMcc** [comment]
We appear to have resolved this by using BulkDelete instead

```
context.Filters.Where(x => x.Key == key).DeleteFromQuery(); // Before
context.BulkDelete(context.Filters.Where(x => x.Key == key), HelperUtil.BulkOptions); // After
```

**Comment by JonathanMagnan** [comment]
Hello @BlairMcc ,

Thank you for reporting.

We will still look at it since that means the `DeleteFromQuery` still have an issue if I understand your solution correctly.

**Comment by BlairMcc** [comment]
> Hello @BlairMcc ,
> 
> Thank you for reporting.
> 
> We will still look at it since that means the `DeleteFromQuery` still have an issue if I understand your solution correctly.

Hey Jonathan, yeah we were unable to resolve the error while retaining the use DeleteFromQuery

**Comment by JonathanMagnan** [comment]
Hello @BlairMcc ,

Could you give the full path of our DLL that's used in your application? (or at least the end)

Such as: 
`C:\Repos\ZZZ\Z.EntityFramework.Plus\packages\Z.EntityFramework.Extensions.5.1.4\lib\net45\Z.EntityFramework.Extensions.dll`

It will give us information about the version and the framework used.

Unfortunately, we are not able to reproduce it and the .NET Standard version cannot use the code from `Z.BulkOperations.BulkOperation`1.DeleteFromQuery` exactly because of the `System.Data.Linq` so perhaps by having the path, it will confirm us our hypothesis.

Obviously, if you can provide a runnable project with the issue, that would be even better.

Best Regards,

Jon

**Comment by BlairMcc** [comment]
Hey @JonathanMagnan ,

Sorry for the delay, but just came across this when using UpdateFromQuery as well

The path is 
```C:\Users\blair\.nuget\packages\z.entityframework.extensions\3.16.16\lib\net45\Z.EntityFramework.Extensions.dll

**Comment by JonathanMagnan** [comment]
Thank,

Do you have a custom server installation? The `System.Data.Linq` is normally part of the .NET Framework and found here by example for my computer: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.Linq.dll

I'm a little bit confused, you initially said you were on .NET Core 3.1 ("call common code from a .Net Core 3.1 Windows Service"), but the reference path say you are using the ".net45" dll (C:\Users\blair\.nuget\packages\z.entityframework.extensions\3.16.16\lib\net45\Z.EntityFramework.Extensions.dll)

Could you let us know more about your special configuration?

At this moment, the error is thrown because this dll is missing

Best Regards,

Jon

**Comment by BlairMcc** [comment]
Hi Jon,

Yeah our codebase is a bit of a WIP as part of some modernisation work

Currently we have a .Net Core 3.1 Worker Service that loads .Net Standard 2.0 plugins with EntityFramework 6.4.0 and Z.EF.Ext 3.16.16. A less than ideal scenario it must be said. We've got some work lined up to move the plugins to NS2.1 and update Z.EF.Ext to 4.0.53 (seemingly the most recent version our company license supports), which hopefully should sort out any oddities we've created on our end

**Comment by JonathanMagnan** [comment]
Not so much we can really do here. 

What you could try is using Entity Framework Plus: https://entityframework-plus.net/batch-delete
- `Delete()` instead of `DeleteFromQuery()`
- `Update()` instead of `UpdateFromQuery()`

In "theory", the `System.Data.Linq` dll is not longer required so it should not throw the error.

One alternative solution would be to force the "EF Plus" resolution such as:

```csharp
ctx.Customers.UpdateFromQuery(x => new Customer() { IsSoftDeleted = true, options =>
			{
				options.InternalIsEntityFrameworkPlus = true;
			});
```

again, this logic path should not require the dll so in theory everything could work.

Could you try it and let us know if that was working? It will be hard for us to test it since your environment is special but we highly believe that it will works.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @BlairMcc ,

Since our last conversation, we haven't heard from you. 

Did you get the chance to test one of the 2 provided solutions?

Don't hesitate to contact us with any questions or further assistance. 

Jon

**Comment by JonathanMagnan** [comment]
Hello @BlairMcc 

A simple reminder that we are here to assist you!

Don't hesitate to contact us once you test one of the 2 provided solutions. 

Best regards,

Jon

**Comment by BlairMcc** [comment]
Hey Jon,

So just getting around to this now, updated to .Net Standard 2.1, EF 6.4.4, Z.EF.Extensions 4.0.53

And getting this error with DeleteFromQuery

```   
Could not load file or assembly 'System.Data.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
at .( )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation`1.DeleteFromQuery(IQueryable originalQuery, IQueryable query)
   at DbContextExtensions.[](IQueryable`1 , Action`1 , CancellationToken )
   at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query, Action`1 bulkOperationFactory)
   at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query)
```
Where the path to the dll is

```
C:\Users\blair\.nuget\packages\z.entityframework.extensions\4.0.53\lib\netstandard2.1\Z.EntityFramework.Extensions.dll
```

**Comment by JonathanMagnan** [comment]
Hello @BlairMcc ,

Have you tried to use the `Delete` method from EF Plus as previously suggested or use the options `options.InternalIsEntityFrameworkPlus = true;`?

From the stack trace, we can easily see that the `DeleteFromQuery` with the old logic (which use `System.Data.Linq`) is used.

When using one of the two provided solutions, the `DeleteFromQuery` will never go in the "Z.BulkOperations.BulkOperation" namespace, so this error will not be throw.

**Comment by BlairMcc** [comment]
That works, thank you for the advise Jon!
