### ISSUE TITLE
Bulk Delete vs Batch Delete?

### ISSUE THREAD

**Issue by jaxidian** [zzzprojects/EntityFramework-Extensions#38]
Hi,

Is there a difference between the two deletes with [EF Extensions](http://entityframework-extensions.net/) vs [EF Plus](http://entityframework-plus.net/)?

**EF Extensions:**
```
context.Customers
    .Where(x => x.LastLogin < DateTime.Now.AddYears(-2))
    .DeleteFromQuery(operation => operation.BatchSize = 10000);
```

**EF Plus:**
```
ctx.Users.Where(x => x.LastLoginDate < DateTime.Now.AddYears(-2))
         .Delete(x => x.BatchSize = 1000);
```

I'm curious if there is an added benefit to one versus the other where I might want to also reference EF+ or if they're effectively duplicated functionality where I should **only** use EF Extensions?

**Comment by JonathanMagnan** [comment]
Hello @jaxidian ,

That's a good question.

Both are almost similar.

EF Extension version support only SQL Server but a few more exceptional case.
EF Plus version support currently more than only SQL Server

There is some slight difference in the conception, but I don't think it worths to talk in deep how they have been done. In short, you should be able to use any of them. I normally recommend on Stack Overflow the EF+ version since it's free!

When the code for the next version is re-written, only one version will be kept since it makes no sense to support two different versions.

Let me know if that answer to your question.

Best Regards,

Jonathan

**Comment by jaxidian** [comment]
Good enough for me. I'm interested only in SQL Server at this time, so I'll just stick to EF Extensions. 👍
