### ISSUE TITLE
Type not supported yet: ınt32

### ISSUE THREAD

**Issue by jertal** [zzzprojects/EntityFramework-Extensions#4]
I am trying to perform bulk operations from LINQ Query without loading entities in the context.

                    entities.PurchasingStepResult.Where(
                          ps => ps.PurchasingStepId == purchasingStepId)
                          .UpdateFromQuery(psr => new PurchasingStepResult { Status = true });

I am getting the error in the header text.I don't have inner exception at all.Stack trace gives the following path.

   at  . . (String )
   at  . . (Property )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at  . . . (SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at  . . (Schema  , Boolean  )
   at  . . (Schema  , Boolean  )
   at  . . (String , String , String )
   at  . . (DbContext )
   at  . . (DbContext )
   at DbContextExtensions.GetModel(DbContext this)
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression)

**Comment by zzzprojects** [comment]
Thank you for reporting,

It seems our library throw an issue when reading your model (The issue look to happen in the GetModel method),

The only way to fix it is by sending us your model
info@zzzprojects.com

**Database First** 
Simply send us your .edmx file.

**Code First**
```csharp
public string GetModelXDocument(DbContext context)
{
    XDocument doc;
    using (var memoryStream = new MemoryStream())
    {
        using (XmlWriter xmlWriter = XmlWriter.Create(memoryStream, new XmlWriterSettings { Indent = true }))
        {
            EdmxWriter.WriteEdmx(context, xmlWriter);
        }

        memoryStream.Position = 0;

        doc = XDocument.Load(memoryStream);
    }
    return doc.ToString();
}
```

_Note: All models sent to us will remain private and will never be used for public usage._

**Comment by jertal** [comment]
I've sent .edmx file from tayyar.atalan@hotmail.com with this subject.

Thanks for your support.

**Comment by jertal** [comment]
Date: Mon, 16 May 2016 04:43:44 -0700

**Comment by jertal** [comment]
Hi
I am using  3.9.32 version of  Z.EntityFramework.Extensions. Also it is  .NET45 and OS Language is en-US.

İf additional information is needed ,i will provide them with pleasure.Thank you for your support.

Best Regards

**Comment by zzzprojects** [comment]
Hello again Tayyar,

We did more test today but unfortunately we still cannot reproduce it. The error makes no sense since it happens when we look in a dictionary, and it contains the key “int32”

We are obviously missing something.

Since all our try to reproduce it failed, we attached a test project in this email using your context.

Can you try it in your environment and let me know if you still have the issue? We did exactly what has posted in the forum. You must change the connection string for your environment prior testing it. If you still have the issue, we will send you another version using the code which throws the error.

As soon as we can reproduce it, we will make the fix and release a new version.                  

Best Regards,

Jonathan

**Comment by jertal** [comment]
Hi Jonathan,
i tried the test project and i still have this issue.There is something attached to my mind about this issue.I am getting the error in lower case "ınt32".I have told you that the OS language is "en-Us" but 
I think somehow it can be upper/lower case issue.

Thank you for your support.
Best Regards
Tayyar

**Comment by zzzprojects** [comment]
Nice, we was hoping you still had this issue (obviously, the project was working from our side).

We thought also about case sensibility but we already use the method "ToLower" to make sure this kind of error do not happen.

```
public static Type ToType(this string name)
{
	name = name.ToLower();

	if (LazyType.Value.ContainsKey(name))
	{
		return LazyType.Value[name];
	}

	throw new Exception(string.Format("Type not supported yet: {0}", name));
}

public static Lazy<Dictionary<string, Type>> LazyType = new Lazy<Dictionary<string, Type>>(() =>
{
	var dict = new Dictionary<string, Type>();

	dict.Add("int16", typeof (short));
	dict.Add("int32", typeof (int));
	dict.Add("int64", typeof (long));
	
	// ... code...
 
	return dict;
});
```

We will send you another project containing the partial code, this will be easier to solve it using the code source.

We believe still are caused by string comparison, but our OS also use "en-US"

**Comment by zzzprojects** [comment]
The issue has been confirmed with Tayyar.

All string comparisons will be verified to use InvariantCulture property.

Example:

```
{
    var int32 = "Int32";
    var b = int32.ToLower() == "int32"; // b == true
}

{
    CultureInfo.CurrentCulture = new CultureInfo("tr-TR");
    Thread.CurrentThread.CurrentCulture = new CultureInfo("tr-TR");
    var int32 = "Int32";
    var b = int32.ToLower() == "int32"; // b == false
}

```

**Comment by zzzprojects** [comment]
The version 3.9.34 fixing the issue with some culture like "tr-TR" has been released : https://www.nuget.org/packages/Z.EntityFramework.Extensions/

Let us know if the bug has been fixed for you.

**Comment by jertal** [comment]
The new version fixed the issue.

Thank you for all your support.
İt helped me a lot  with admirable bulk update performance.

Best Regards
Tayyar
