### ISSUE TITLE
BulkSynchronize does not work with IncludeGraph=true

### ISSUE THREAD

**Issue by ilushka85** [zzzprojects/EntityFramework-Extensions#414]
EF Core

If we use includegraph=true child entries are not inserted.  If we use bulkinsert + include graph everything works fine.

**Comment by JonathanMagnan** [comment]
Hello @ilushka85 ,

That's by design,

`IncludeGraph` only works for `BulkInsert`, `BulkUpdate`, and `BulkMerge`.

It never has worked for `BulkDelete` and `BulkSynchronize` (anything with a "delete").

Due to the complexity behind supporting correctly the `delete`, I don't think we will ever try again.

Best Regards,

Jon
