### ISSUE TITLE
BUlkInsert into inherited class causes the following error

### ISSUE THREAD

**Issue by proforce2k** [zzzprojects/EntityFramework-Extensions#43]
Exception of type 'EntityFramework.MappingAPI.Exceptions.ParentNotMappedYetException' was thrown.
   at EntityFramework.MappingAPI.Mappers.CodeFirstMapper.PrepareMapping(String typeFullName, EdmType edmItem) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Mappers\CodeFirstMapper.cs:line 51}

**Comment by JonathanMagnan** [comment]
Hello @proforce2k ,

The EntityFramework.MappingAPI (https://efmappingapi.codeplex.com/) is not supported since 2014.

Our library Entity Framework Extensions doesn't use this library. So you are likely using EntityFramework.BulkInsert which is not supported as well since 2014.

We currently only support our PAID library [Entity Framework Extensions](http://entityframework-extensions.net/).

Let me know if you need more explanation.

Best Regards,

Jonathan

**Comment by proforce2k** [comment]
Great, thanks for getting back to me. Will purchase a licence when Im a bit further down the line with this project.

**Comment by JonathanMagnan** [comment]
Closing Comment: Issue/Question answered
