### ISSUE TITLE
BulkInsert with computed column

### ISSUE THREAD

**Issue by rzframe** [zzzprojects/EntityFramework-Extensions#431]
### Description
Using bulkinesrt on a table that has computed column. Getting below exception. Works fine if there is no computed column.

### Exception
Column 'inserted.Average' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause.

### Fiddle or Project (Optional)
Context.BulkInsert<TEntity>(listOEntity);

**Comment by JonathanMagnan** [comment]
Hello @rzframe ,

There are a few scenarios that our library that cannot discover the column in the database has some special logic like in your case.

To solve it, you need to specify the following options: `option.ForceSelectOutput = true`

When true and outputting some value, our library will create a table variable and will output value in this table instead of performing directly a select.

Let me know if that solution can work for you.

Best Regards,

Jon

**Comment by rzframe** [comment]
Thank you and that worked.
