### ISSUE TITLE
BulkSaveChangesAsync throws SqlException when updating entities with transaction level Snapshot Isolation

### ISSUE THREAD

**Issue by d-57u3ndl** [zzzprojects/EntityFramework-Extensions#475]
Hello @JonathanMagnan ,
I have updated from version 4.0.61 to 6.13.10, because of the new `autoTruncate` option.
Unfortunately, I had to determine that there might be a bug in version 6.13.10 in relation with transaction level `Snapshot Isolation` and `BulkSaveChangesAsync`.

Steps to reproduce:
1) Insert 100 entities in empty Table
2) Create a transaction with transaction level `Snapshot Isolation`
3) Update the 100 presiously inserted entities
4) Call `BulkSaveChangesAsync` => Exception gets thrown

### Exception
The EF ZExtensions are creating this SQL Script:
```
CREATE TABLE #ZZZProjects_b0ffa23a_c827_4a05_aec1_eb907a9d97ca ( [InsteadOfPrice] decimal(18, 4) NULL, [SollDb] decimal(18, 4) NULL, ZZZPredicate_2 varchar(16) 
COLLATE Latin1_General_CI_AS NULL, ZZZ_Index [INT] NOT NULL )    
CREATE CLUSTERED INDEX [INDEX_#ZZZProjects_b0ffa23a_c827_4a05_aec1_eb907a9d97ca] ON #ZZZProjects_b0ffa23a_c827_4a05_aec1_eb907a9d97ca (ZZZ_Index ASC);  

CREATE TABLE #ZZZProjects_364364f8_bb21_4623_80c8_4128543e8092 ( [SollDb] decimal(18, 4) NULL, ZZZPredicate_1 varchar(16) COLLATE Latin1_General_CI_AS NULL, ZZZ_Index [INT] NOT NULL )   
CREATE CLUSTERED INDEX [INDEX_#ZZZProjects_364364f8_bb21_4623_80c8_4128543e8092] ON #ZZZProjects_364364f8_bb21_4623_80c8_4128543e8092 (ZZZ_Index ASC);  

CREATE TABLE #ZZZProjects_3d0857e8_661f_416d_8d1f_5946edc8ff85 ( [InsteadOfPrice] decimal(18, 4) NULL, ZZZPredicate_1 varchar(16) COLLATE Latin1_General_CI_AS NULL, ZZZ_Index [INT] NOT NULL )    
CREATE CLUSTERED INDEX [INDEX_#ZZZProjects_3d0857e8_661f_416d_8d1f_5946edc8ff85] ON #ZZZProjects_3d0857e8_661f_416d_8d1f_5946edc8ff85 (ZZZ_Index ASC);  

CREATE TABLE #ZZZProjects_14612bde_896e_4b7c_94a8_5a7e2394bf5a ( [AdvertisingPrice] decimal(18, 4) NULL, [SollDb] decimal(18, 4) NULL, ZZZPredicate_2 varchar(16) COLLATE Latin1_General_CI_AS NULL, ZZZ_Index [INT] NOT NULL )   
CREATE CLUSTERED INDEX [INDEX_#ZZZProjects_14612bde_896e_4b7c_94a8_5a7e2394bf5a] 
ON #ZZZProjects_14612bde_896e_4b7c_94a8_5a7e2394bf5a (ZZZ_Index ASC);  
```
Which leads to following Exception Message, because of TransactionLevel Snapshot Isolation:
```
System.Data.SqlClient.SqlException: Transaction failed because this DDL statement is not allowed inside a snapshot isolation transaction. Since metadata is not versioned, a metadata change can lead to inconsistency if mixed within snapshot isolation.
```

A possible solution approach could be described here:
[https://dba.stackexchange.com/questions/206804/why-is-it-not-possible-to-create-indexes-on-temp-tables-in-snapshot-isolation](url)

### Further technical details
- EF version: 6.2.0
- EF Extensions version: 6.13.10 (with version 4.0.61 the update operation worked as expected)
- Database Provider: Microsoft SQL Server 2016 (SP3) (KB5003279) - 13.0.6300.2 (X64)

Please let me know if you need any further technical information.

**Comment by JonathanMagnan** [comment]
Hello @d-57u3ndl 

Could you try again with the option `options.DisableTemporaryTableClusteredIndex = true;` ?

You can also disable it globally this way:

```csharp
// Global
EntityFrameworkManager.BulkOperationBuilder = builder => builder.DisableTemporaryTableClusteredIndex = true;
```

Also, it is possible to have a runnable project with this issue?

Our library already has a logic to don't create an index when this isolation level is used: `if(command.Transaction != null && command.Transaction.IsolationLevel == IsolationLevel.Snapshot) ...`

We already have some tests that follow exactly your step to reproduce so perhaps something else is missing which doesn't allow our library to currently see your `IsolationLevel`.

Best Regards,

Jon

**Comment by rizi** [comment]
> ```cs
> DisableTemporaryTableClusteredIndex 
> ```

@JonathanMagnan using options.DisableTemporaryTableClusteredIndex = true fixes the problem --> but I think this should be handled by the library itself.

Here is a very simple sample to reproduce the issue.
https://drive.google.com/file/d/1vP_IYDAyFZXj-tdy5dQbLea-yK7UB6dF/view?usp=sharing

Before you can execute the tests you have to use Create_Database_And_Create_Table.sql to create the database and the table needed for the tests. (you can find the script in the sample project).

We have to tests

 # Insert_More_Than_90_Items_Should_Not_Fail_But_Fails_With_DDL_Statement_Is_Not_Allowed_Inside_A_SnapshotIsolation_Transaction is red but should work --> this test fails without setting DisableTemporaryTableClusteredIndex to true --> but I think it should be green

 
 # Insert_One_Item_Should_Insert_One_Item --> this test works as expected, because it only inserts one item to the database.

It seems the number of items that should be added are relevant (it seems that for one element the sqlcommand is used and for more elements the bulkinsert class is used)

Do you think you could provide a fix so we don't need to use options.DisableTemporaryTableClusteredIndex?

Br

**Comment by JonathanMagnan** [comment]
Hello @rizi ,

Thank you for the project, my developer will look at it.

I also agree with you that if our library could handle it, it should handle it.

**Comment by rizi** [comment]
> Hello @rizi ,
> 
> The v6.13.15 has been released.
> 
> Could you double-check on your side if everything is working as expected? We should now handle the `Snapshot` isolation level correctly when used with a `TransactionScope`.
> 
> Best Regards,
> 
> Jon

@JonathanMagnan thx for the fast fix, I can confirm that it's working now.

Thank you very much.
