### ISSUE TITLE
BulkInsert writes incorrect boolean value when .HasDefaultValue is specified

### ISSUE THREAD

**Issue by virzak** [zzzprojects/EntityFramework-Extensions#481]
### Description
When .HasDefaultValue(false) is specified, BulkInsert does not care the actual value.

### Fiddle or Project (Optional)
https://dotnetfiddle.net/RGmgw5

### Further technical details
- EF version: 6.0.4
- EF Extensions version: 6.13.17
- Database Provider: Sql Server

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

Unfortunately, that's currently a limitation of our `BulkInsert`.

It currently always take the `HasDefaultValue` for performance reason (we don't want to check every entity if a value has been specified or not by default).

It is possible to specify a value by forcing a `ForceValueGeneratedStrategy`:

```csharp
context.BulkInsert(new[] { entity }, options => options.ForceValueGeneratedStrategy = Z.EntityFramework.Extensions.ValueGeneratedStrategyType.OnAdd);
```

We hope to eventually to solve this scenario to be closer of `EF Core` behavior but at this moment, that's the only possible solution with the `BulkInsert`.

Another alternative solution would be to use the `BulkSaveChanges` which already handle this correctly:

```csharp
context.Add(entity);
context.BulkSaveChanges();
```

Let me know if that answers correctly to your question.

Best Regards,

Jon

**Comment by virzak** [comment]
Everything started working fine when I dropped `HasDefaultValue`. It was `false` for boolean, which is the default anyways. 

Does the performance gain only happens when `HasDefaultValue` is there? And if so what's the difference in perf?

The biggest concern from a consumer point of view are the bugs this could cause by the unsuspecting user. And I would probably expect to see this scenario in the [limitations section](https://entityframework-extensions.net/bulk-insert#limitations)

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

It is pretty much the same performance if you set the `HasDefaultValue` or not. That's not exactly where the performance problem is.

The thing we cannot do because of the performance is to look at every column with a default to check if a value different than the default value. In your Fiddle, you set an `HasDefaultValue` but you also specify a value and this is the part we choose not to do at this moment. 

Usually, this is not the common scenario (at least, not from our perspective) and we don't want to slow down the bulk operation for everyone else by having to check every entity when people might not need this check.

**Comment by virzak** [comment]
I think I get it. If you have 100 columns and 90 of them have a default value, you'd rather deal with 10 columns instead of 100. Correct?

Does that mean that the more default values there are in a table, the faster the insert is?

Also, is there an option to use `ForceValueGeneratedStrategy` per column so that if 11th column is checked without checking all 100?

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

That's not exactly like this.

There is a big difference between `HasDefaultValue` and `HasDefaultValueSql`.

`HasDefaultValue`: will set a default value where in the application run
`HasDefaultValueSql`: will set a default value in the database column

## HasDefaultValue

Our library by default will always include those columns in part of the insert as the value is generated in the application. So always 100 columns will be included (90 of those will have the value specified in the `HasDefaultValue`).

## HasDefaultValueSql

Our library will not include those columns in part of the insert but will need to retrieve the value from the database since it has been generated in the database. So in this case, 10 columns will be included.

## Both cases

In both cases, if you specify your own value, we will not check if you have specified one or not for the `BulkInsert` as it takes some time to look at every entity/property to check a value has been specified or not (and also make the SQL to execute more complex).

## ForceValueGeneratedStrategy

This option will only check already only for a column that has either a `HasDefaultValue` or `HasDefaultValueSql`. If nothing is specified, the option will never be executed for the column.
