### ISSUE TITLE
Azure SQL Server - slow BulkUpdate operation for 4k entries

### ISSUE THREAD

**Issue by ta6636** [zzzprojects/EntityFramework-Extensions#482]
### Description
I have SQL Server in Azure (Standard S3: 100 DTUs). With using EFCore within the .NET 6 project, I try to update around 4k entries, which runs for 20 seconds. Why ?

While loading entries from `DbContext`, I use `AsNoTracking()` method. For saving the changes, I simply call `await _sqlContext.BulkUpdateAsync(entries, cancellationToken);`

### Further technical details
- EF version: 6.0.3
- EF Extensions version: 6.13.17
- Database Provider: Azure SQL Server

**Comment by JonathanMagnan** [comment]
Hello @ta6636 ,

How long does it take on a non-azure environment?

Unfortunately on a lower tier, SQL Azure is really good (at least was doing in the past) at doing throttle and slowing everything down and in particular `SqlBulkCopy`.

Even a simple `SELECT 1` could take up to 100ms to get executed (in basic tier).

So if possible, the first thing you should try to see if the problem is `SQL Azure` or not is executing the same `Bulk Update` on a non `SQL Azure` environment just to be able to compare at least the time it takes to get executed.

Let me know the result if you can do this test.

Best Regards,

Jon
