### ISSUE TITLE
How to use both v5 (EF6) and v3 (EFCore 3.1) in the same project

### ISSUE THREAD

**Issue by Bouke** [zzzprojects/EntityFramework-Extensions#493]
When introducing the extensions for EF3.1, I'm met with the following compilation error:

### Exception
DataWarehouseDbContext.cs(103, 9): [CS0433] The type 'DbContextExtensions' exists in both 'Z.EntityFramework.Extensions.EFCore, Version=3.13.1.0, Culture=neutral, PublicKeyToken=59b66d028979105b' and 'Z.EntityFramework.Extensions, Version=5.1.15.0, Culture=neutral, PublicKeyToken=59b66d028979105b'

How can I use both versions in the same project? All extension methods are defined on the root-namespace, which in itself is a major concern and not aligned with proper c# design.

**Comment by JonathanMagnan** [comment]
Hello Bouke,

To make it works, you will need to use extern alias: https://blogs.msdn.microsoft.com/ansonh/2006/09/27/extern-alias-walkthrough/

In this way, you will be able to add both libraries to the same project and choose which one for each file you would like to use.

Unfortunately, there is no easy way to make it works since as you said, our extension methods are in the root namespace.

Let me know if you need more help with extern alias.

Best Regards,

Jon
