### ISSUE TITLE
Support of Effort database

### ISSUE THREAD

**Issue by Jerome2606** [zzzprojects/EntityFramework-Extensions#52]
I'm using https://github.com/tamasflamich/effort for my testing.

It's useful to make functional test using Entity Framework 6 because it get me back error like Foreign key violation, duplicate key, problem with attached entity, ...

But it's not working anymore with the use of this extension:
"Oops! The destination table name could not be found. That typically happen for an unsupported provider. If you use a custom connection, contact us to learn how to setup it within our library."

What can I do to make it working ?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @Jerome2606 ,

On your side, you cannot do anything.

However, we will look on it on our side during the weekend.

Best Regards,

Jonathan

**Comment by Jerome2606** [comment]
Hello,

Super
Thank you very much,

Jerome

**Comment by JonathanMagnan** [comment]
Hello @Jerome2606 ,

Just to let you know that we were, unfortunately, able to find time for this request during the weekend.

It's planned to look at it and hopes to complete it tomorrow (Wednesday).

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Well, in fact, I started to look at it a few minutes ago since I remembered that `Effort` is a `MemoryDatabase`.

What do you expect we support?

We can for sure "support" BulkSaveChanges by simply calling instead "SaveChanges" in our library but I don't think we will be able to support bulk operations such as `BulkInsert`, `BulkUpdate`, `BulkDelete`, and `BulkMerge`.

Best Regards,

Jonathan

**Comment by Jerome2606** [comment]
Can't you make it support by making a foreach insert, update and delete if it is a MemoryDatabase ?

Actually I use my unit test to test my code. The advantage of EffortDb is that it's use Entity Framework so it allow me to debug in unit test bad use of state of entities etc.

I expect to make my unit test not throwing error when I use this extension.

Regards,

Jerome

**Comment by JonathanMagnan** [comment]
Hello @Jerome2606 ,

Unfortunately, that's not as simple as this.

`Bulk Operations` allow making some customization as choosing a custom primary key, column to update, column, SQL formula, etc. Some of them cannot be so easily done under `EffortDb` and some of them cannot be done at all.

When I saw this request, I first though `EffortDb` was a wrapper such as `Glimpse` or `HibernatingRhinos` (It was probably late!), so that's why I didn't see any problem to support it but that's obviously not the case!

There is some stuff that we can support, but that will be only some kind of workaround

By example:
- BulkSaveChanges will call automatically SaveChanges
- BulkInsert will create a new context, add entity, and call SaveChanges
- BulkUpdate will create a new context, set entity state to modified, and call SaveChanges
- BulkDelete will create a new context, set entity state to deleted, and call SaveChanges

Doing something such like this doesn't make sense either since, at the end, our library will not be used at all.

Here is currently the problem I see with this request.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jerome2606 ,

I will close this request since I don't think there is a chance we support Effort since that will mean to skip almost all functionalities of our library.

Best Regards,

Jonathan

**Comment by Jerome2606** [comment]
Ok no problem

**Comment by Prayfort** [comment]
Hello @JonathanMagnan ,

The Effort project recently became part of zzzProjects.  Could there be a way to use the bulk functions in a unit test with "Effort" in the future?

**Comment by JonathanMagnan** [comment]
Hello @Prayfort ,

There is a good chance ;)

Must if we do it, that will probably be in late 2018 since we have a way to many projects currently.

Best Regards,

Jonathan
