### ISSUE TITLE
Bulk synchronize problem with not null columns

### ISSUE THREAD

**Issue by jaroslawrutk** [zzzprojects/EntityFramework-Extensions#551]
### Description

I want to use : https://entityframework-extensions.net/bulk-extensions but durring processing im getting error: Cannot insert the value NULL into column 'XXX', table 'XXX'; column does not allow nulls. And that's true, but i have configured dbcontext with this column makred as required:

            builder.Property(x => x.XXX)
                .HasColumnName("XXX")
                .IsRequired();
Method used is in that way

            await ImportDbContext.Set<ENTITY>()
                .BulkSynchronizeAsync(ENTITY, options =>
            {
                options.ColumnPrimaryKeyExpression = entity => entity .XXX;
                options.SynchronizeKeepidentity = true;
            });
In logs i saw that extension creating own cache table where this column is marked as possible null... so propably this problem is here, extensions dont recognize that column should be notnull... I have DbFirst approach.

Please help me with that case or maybe there is better extension to EF to Bulk operations.

### Exception
Cannot insert the value NULL into column 'XXX', table 'XXX'

```
Exception message: Cannot insert the value NULL into column 'XXX', table 'XXX'
```

**Comment by jaroslawrutk** [comment]
It's working with:                
                options.ColumnInputExpression = x => new 
                {
                    x.ColumnName1,
                    x.ColumnName2,
                    x.ColumnName3,
                    x.ColumnName4,
                    x.ColumnName5,
                    x.ColumnName6,
                    x.ColumnName7,
                    x.ColumnName8,
                    x.ColumnName9,
                    x.ColumnName10,
                    x.ColumnName11,
                    x.ColumnName12,
                    x.ColumnName13,
                };
but it's not elegant solution :D

**Comment by JonathanMagnan** [comment]
Hello @jaroslawrutk ,

I answered on Stack Overflow: https://stackoverflow.com/questions/77329834/bulk-methods-are-throwing-cannot-insert-the-value-null-into-column-ef-extensio

The current solution to specifies the [ColumnInputExpression](https://entityframework-extensions.net/column-input-expression) to choose the column to insert or update with the [EF Core Bulk Synchronize](https://entityframework-extensions.net/bulk-synchronize) currently work because you told our library to ignore to insert in your column `XXX`.

If you really don't want to insert on this column, I would recommend you to ignore it instead using the [IgnoreOnSynchronizeInsertExpression](https://entityframework-extensions.net/ignore-on-synchronize-insert-expression).

NOTE: It's already ignored on the update since this is the custom key used.

Let me know if you need more help on this issue.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @jaroslawrutk ,

Since our last conversation, we haven't heard from you. 

Let me know if you need more information. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello again, 

A simple reminder that we are here to assist you. 

Don't hesitate to contact us if you have any questions. 

Best regards, 
Jon
