### ISSUE TITLE
Logging of command parameters / SensitiveDataLogging in batch operations

### ISSUE THREAD

**Issue by Euphoric** [zzzprojects/EntityFramework-Extensions#595]
### Description
We were trying to debug issue in our application, which is using Entity Framework Extensions' bulk operations. We have enabled Entity Framework Core's Sensitive Data Logging, so we could see what data is being saved into database. But we have found out that the bulk insert operations do not output command parameters when Sensitive Data Logging is enabled. When I tried using Entity Framework's own insert logic, it correctly logged the command parameters.

I would expect Entity Framework Extensions to respect Entity Framework's `EnableSensitiveDataLogging` and log command parameters for batch operations.

### Example
Below is how Entity Framework Core logs command with Senstive Data Logging enabled, compared to how Entity Framework Extensions bulk insert logs the command. Both examples are run against same DbContext.

#### Entity Framework Core

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (31ms) [Parameters=[:p0='43370451-3cb1-455c-ade7-c3a8f3982b82' (DbType = Binary), :p1='testValue' (Size = 2000)], CommandType='Text', CommandTimeout='0']
      DECLARE


      BEGIN

      INSERT INTO "Tests" ("Id", "Value")
      VALUES (:p0, :p1);

      END;
````

#### Entity Framework Extensions
````
info: Microsoft.EntityFrameworkCore.Database.Command[0]
      -- Executing Command:
      INSERT  INTO "Tests" ("Id", "Value") VALUES(:P_0, :P_1)
      -- :P_0: System.Object[] (Type = Binary, Size = 16)
      -- :P_1: System.Object[] (Type = String, Size = 2000)
      -- CommandTimeout:120
      -- Executing at 7/10/2024 11:48:11 AM
````

### Further technical details

- EF version: [EF Core v8.0.7]
- EF Extensions version: [EFE Core v8.103.0.0]
- Database Server version: [Oracle XE 21.3.0]
- Database Provider version (NuGet): [Oracle.EntityFrameworkCore 8.23.40]

**Comment by JonathanMagnan** [comment]
Hello @Euphoric ,

I could be wrong, but I believe both log parameters almost the same way.

The major difference is that our library uses Array Binding for inserting (allowing to improve performance when performing multiple inserts), which causes the parameter to be an array of a type (`System.Object[]`) instead of a specific type. Then, values from this array are not shown.

Unfortunately, I don't think we can control this part to show values.

Let me know if that answer to your question even if we do not solve your issue.

Best Regards,

Jon

**Comment by Euphoric** [comment]
Thanks for reply.

I don't understand what "Array Binding" is, nor how EF Extensions is using it to improve performance.

I'm under impression that the log is produced by EF Extensions, not by EF Core. From reading source code, I was unable to identify how EF Core would produce that particular log. As "Executing Command" text is nowhere in EF Core codebase. Could you confirm that the log produced by EF Extensions is not something in EF Extensions codebase?

**Comment by JonathanMagnan** [comment]
Hello @Euphoric ,

I was about to edit my answer to talk about this as I did more research after answering.

Indeed, our library generates the log you currently see.

It could be possible for you to retrieve parameter values from the command itself:

```csharp
context.BulkInsert(list, option =>
{
	// option.UseLogDump = true; // not needed in your case
	// AddLogExecuting option will only work if the log is enabled... Either by enabled it from EF Core itself, using `UseLogDump`, or using `Log`
	
	option.AddLogExecuting = (command, log) =>
	{
		var oracleCommand = (OracleCommand)command;
	};
});
```

Once you get the command, you can access the parameter and log the values in the array or do pretty much anything you want.

If you need it to be automatically done, we could do it by adding a new option that you could enable globally or per operation. We currently doesn't want this as a default behavior since we will dramatically impact people with `BLOB` type for example.

Let me know if the tricks with the `AddLogExecuting` solved your problem or if you wish we add the option to do it automatically in our library.

Best Regards,

Jon

**Comment by Euphoric** [comment]
Thank you for point me to `AddLogExecuting `. That is a possible workaround for our issue.

But I would still expect EF Extensions to respect the `EnableSensitiveDataLogging` flag and log the parameters properly. So I would like to flag that as a feature request.

I would assume EF Core has similar issue with `BLOB` parameters. I would suggest looking at how EF Core does the logging of `BLOB` parameters.

Otherwise, I'm satisfied with your support. You can close this issue.
