### ISSUE TITLE
BulkInsert function is not working properly

### ISSUE THREAD

**Issue by dombaigabor** [zzzprojects/EntityFramework-Extensions#602]
### Description
We upgraded the EF Core to the latest version last month (currently: 8.0.7). We use your library very often for bulk operations. 
We discovered today the BulkInsert function is not inserting BIT (boolean) columns, if it has .HasDefaultValue(false) configuration.

If we check the SQL Server Profiler, columns only show in the "OUTPUT INSERTED" section.

### Exception
There is no exception.

### Fiddle or Project (Optional)
http://dotnetfiddle.net/xnLNFA

### Further technical details

- EF version: EF Core 8.0.7
- EF Extensions version: 8.103.1
- Database Server version: SQL Server 2016
- Database Provider version (NuGet): 5.2.1

**Comment by JonathanMagnan** [comment]
Hello @dombaigabor ,

Indeed, this is the expected behavior by default when using [BulkInsert](https://entityframework-extensions.net/bulk-insert)

However, you can see this behavior with the option [ExplicitValueResolutionMode](https://entityframework-extensions.net/explicit-value-resolution-mode)

See the 3 followings mode:
- AlwaysKeepValueOnInsert
- SmartDefaultValueOnBulkInsert
- SmartPartialResolutionOnBulkInsert

I forked your Fiddle to make your example work: https://dotnetfiddle.net/2ATbHx

Let me know if the article explains correctly the cause and solution for this issue.

Best Regards,

Jon

**Comment by dombaigabor** [comment]
Hey,

Thanks for the really fast answer.
Is there any significant impact for the performance with AlwaysKeepValueOnInsert option? We use an own DataContext interface with an "own" implementation for BulkInsert (it calls yours, with a little entity preparation for our system). I think we should place that option there, but i am afraid of slower inserts of entites which has no default value.

> Hello @dombaigabor ,
> 
> Indeed, this is the expected behavior by default when using [BulkInsert](https://entityframework-extensions.net/bulk-insert)
> 
> However, you can see this behavior with the option [ExplicitValueResolutionMode](https://entityframework-extensions.net/explicit-value-resolution-mode)
> 
> See the 3 followings mode:
> 
> * AlwaysKeepValueOnInsert
> * SmartDefaultValueOnBulkInsert
> * SmartPartialResolutionOnBulkInsert
> 
> I forked your Fiddle to make your example work: https://dotnetfiddle.net/2ATbHx
> 
> Let me know if the article explains correctly the cause and solution for this issue or if you need more assistance
> 
> Best Regards,
> 
> Jon

**Comment by JonathanMagnan** [comment]
Hello @dombaigabor ,

No, the **AlwaysKeepValueOnInsert** state will not significantly impact performance. We will always take the value from the properties instead of ignoring it if that's really the behavior you are looking for. So you must ensure that's really the behavior you want.

For the two other states (I answer in case someone else is looking for it) **SmartDefaultValueOnBulkInsert** and
**SmartPartialResolutionOnBulkInsert**, those states can have a significant performance impact if some entities has values on those properties and some others do not. For example:

- 1 property with default value: can cause our library to create maximum 2 distinct inserts to handle all possibilities
- 2 properties with default values: can cause our library to create maximum 4 distinct inserts to handle all possibilities
- 3 properties with default values: can cause our library to create maximum 8 distinct inserts to handle all possibilities
- And so on...

Let me know if you have any additional questions

Best Regards,

Jon
