### ISSUE TITLE
The latest trial version is invalid

### ISSUE THREAD

**Issue by qiqiwang213** [zzzprojects/EntityFramework-Extensions#611]
I have updated the latest trial package, but I found that I cannot try it properly when accessing the program. The prompt is as follows

System.Exception: An error occurred while updating the entries. See the inner exception for details. ---> System.Exception: ERROR_005: The monthly trial period is expired (date: 2024-11-05, version: 8.103.6.0). You can extend your trial by downloading the latest version as the beginning of every month. If you already have purchased a license, you can find more common causes of this problem here: https://entityframework-extensions.net/trial

**Comment by IkaIkulin** [comment]
Hello,

I'm joining, I have the same problem as everyone else :-(

II

**Comment by ufo2001** [comment]
Same Problem..


ERROR_005: The monthly trial period is expired (date: 2024-11-05, version: 8.103.6.0). You can extend your trial by downloading the latest version as the beginning of every month. If you already have purchased a license, you can find more common causes of this problem here: https://entityframework-extensions.net/trial

**Comment by Glopex** [comment]
Same here, **please** this need to be fixed **as soon as possible**

**Comment by abertolucci92** [comment]
please fix as soon as possible

**Comment by giuliaerre** [comment]
Same problem. please fix!

**Comment by JonathanMagnan** [comment]
Hello, 

Sorry for the inconvenience, we are currently working on releasing a new trial and it will be available shortly. 

The trial expires at the end of each month. We do not recommend that you use the trial in a production machine or client machine; Occasionally, there may be a lapse of a few days between releases. 

That said, we highly suggest that companies purchase a license so that they won’t have to update their production environment every month. 

Don't hesitate to contact us for further information regarding our product. 

Jon

**Comment by haroldGiraldo** [comment]
Same problem. please fix! thanks. They should have a cheaper paid version. I would surely buy

**Comment by JonathanMagnan** [comment]
Hello everyone!

The trial 8.103.6.1 is now available. 

Don’t hesitate to contact us if you need further assistance. 

Best regards, 

Jon
