### ISSUE TITLE
Error when Attempting BulkOperations

### ISSUE THREAD

**Issue by keerthankumarCSnet** [zzzprojects/EntityFramework-Extensions#74]
I get the following error when I try to run BulkOperation on the context.

"A default DbContext context must exist, or a context factory must be provided (EntityFrameworkManager.ContextFactory). This setting is required for some additional features."

I have EntityFramwork as part of the class library. The context once initialized with options is DI'ed across the application.
  public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        {
        }

when I try to perform the bulkopreation using the context object it fails. I understand it is looking for a parameterless constructor. If we add the parameterless constructor it wouldn't have access to the connection string. Since, it is a class Library it I can't add the factory to the startup. Can you please let me know the options.

Thanks,
Keerthan

**Comment by JonathanMagnan** [comment]
Hello @keerthankumarCSnet ,

If you cannot have a `parameterless constructor`, you will need to specify a new context for the `ContextFactory` such as

```csharp
var optionsBuilder = new DbContextOptionsBuilder<EntityContext>();
optionsBuilder.UseSqlServer("Server=XPS8700;Initial Catalog=Z.Test.EntityFramework.Plus.EFCore;Integrated Security=True;");
EntityFrameworkManager.ContextFactory = context => new DbContext(optionsBuilder.Options);
```

The options passed doesn't really matter since we change them for the used context.

Creating a new context is a new requirement for our `EFE Core` since it allow us to use some `Entity Framework` method without affecting your context.

I hope this clarified everything. If you still have questions, we are always here to answer.

Best Regards,

Jonathan

**Comment by keerthankumarCSnet** [comment]
Jonathan,

Thanks, that worked !

Keerthan

**Comment by JonathanMagnan** [comment]
Hello @keerthankumarCSnet ,

We added a new page in our documentation about the Context Factory: http://entityframework-extensions.net/context-factory

Soon, we will have all our example working online with https://dotnetfiddle.net/

Best Regards,

Jonathan
