### ISSUE TITLE
BulkMerge fails to insert data

### ISSUE THREAD

**Issue by halkar** [zzzprojects/EntityFramework-Extensions#82]
Hi!

I'm getting this error
`SqlException: Attempting to set a non-NULL-able column's value to NULL.`

```
dbContext.BulkMerge(persons, options =>
{
    options.IncludeGraph = true;
    options.IncludeGraphOperationBuilder = operation =>
    {
        if (operation is BulkOperation<SecurityManagement_User>)
        {
            var bulk = (BulkOperation<SecurityManagement_User>)operation;
            bulk.ColumnPrimaryKeyExpression = x => x.KeyField;
        }
        else if (operation is BulkOperation<CommonManagement_Person>)
        {
            var bulk = (BulkOperation<CommonManagement_Person>)operation;
            bulk.ColumnPrimaryKeyExpression = x => x.KeyField;
        }
    };
});
```

No information about the field is provided in the exception.

**Comment by JonathanMagnan** [comment]
Hello @halkar ,

Yes, this is a SQL Exception so we don't know either about the field or value in error.

I recommend you to reduce the batch size to debug this scenario and use SQL Profiler:

```csharp
context.BulkMerge(list, options =>
    {
        options.ColumnPrimaryKeyExpression = x => x.ColumnInt;
        options.BatchSize = 10;
    }
);
```

Using SQL Profiler, you will find out which statements are in error and be able to check which column has a null value and if that's normal.

Let me know if you need some help for this.

Best Regards,

Jonathan

**Comment by halkar** [comment]
When I add `BatchSize` everything is fine. This code works like a charm.

```
dbContext.BulkMerge(persons, options =>
{
    options.IncludeGraph = true;
    options.IncludeGraphOperationBuilder = operation =>
    {
        if (operation is BulkOperation<SecurityManagement_User>)
        {
            var bulk = (BulkOperation<SecurityManagement_MbsUser>)operation;
            bulk.ColumnPrimaryKeyExpression = x => x.KeyField;
            bulk.BatchSize = 100;
        }
        else if (operation is BulkOperation<CommonManagement_Person>)
        {
            var bulk = (BulkOperation<CommonManagement_Person>)operation;
            bulk.ColumnPrimaryKeyExpression = x => x.KeyField;
            bulk.BatchSize = 100;
        }
    };
});
```

**Comment by halkar** [comment]
But if change `BatchSize` to 1000 it starts to fail.

**Comment by JonathanMagnan** [comment]
Hello @halkar ,

I'm not sure if that's possible but do you think you could provide us an example of this issue?

Modifying the batch size should not have any impact here.

It's possible that your table has some trigger which could cause this issue?

**Comment by halkar** [comment]
@JonathanMagnan I'll try to create a sample.

**Comment by JonathanMagnan** [comment]
Hello @halkar ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

**Comment by luciniga** [comment]
@JonathanMagnan I am running into the same issue with the latest version of the framework (6.13.8) and I'm experiencing the same symptoms as @halkar: if I use a BatchSize of 100-200, I don't get any errors. If I use a batch size of 500, it fails.

I've tried using SQL Server Profiler to look over the queries that the framework generates, but that doesn't help me much, because they do not contain a lot of information. E.g. the actual row values are not contained in those queries.

Can you recommend a way to debug this? Is there a way to query the temp tables (#ZZZ...) that the framework creates? I'm trying to get to the bottom of this in order to see what the correct fix should be for my problem. I'm suspecting that it might have something to do with the amount of data that needs to be saved. One of the text columns can have up to 1000 chars.

**Comment by jaypalexa** [comment]
I have just emailed a small .NET 6.0 console app solution with minimal code to reproduce the issue to [info@zzzprojects.com](mailto:info@zzzprojects.com).  Hope that you are able to re-create and solve.
